-- Source sandbox: bounded parents referenced by spatial rows.
select clock_timestamp()::text as observed_at,jsonb_agg(x order by source_relation) as relations from (select 'public.articles' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from public.articles p where p.id in (select article_id as id from spatial.evidence_artifact_registry where article_id is not null)
union all
select 'public.geographic_places' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from public.geographic_places p where p.id in (select canonical_place_id as id from spatial.assertion_revisions union select canonical_place_id from spatial.geometry_snapshots union select canonical_place_id from spatial.place_authority_snapshots)
union all
select 'public.nodes' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from public.nodes p where p.id in (select graph_node_id as id from spatial.assertions union select graph_node_id from spatial.graph_node_authority_snapshots)
union all
select 'public.policy_documents' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from public.policy_documents p where p.id in (select policy_document_id as id from spatial.evidence_artifact_registry where policy_document_id is not null)
union all
select 'public.source_change_events' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from public.source_change_events p where p.id in (select source_change_event_id as id from spatial.evidence_condition_events where source_change_event_id is not null)) x;

-- Survivor: archived parents and declared references.
select clock_timestamp()::text as observed_at,jsonb_agg(x order by source_relation) as relations from (select 'public.articles' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(payload order by source_key),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from mip_private.spatial_row_versions where source_project='jfnzyvzthzqtczlxhjll' and source_relation='public.articles'
union all
select 'public.geographic_places' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(payload order by source_key),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from mip_private.spatial_row_versions where source_project='jfnzyvzthzqtczlxhjll' and source_relation='public.geographic_places'
union all
select 'public.nodes' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(payload order by source_key),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from mip_private.spatial_row_versions where source_project='jfnzyvzthzqtczlxhjll' and source_relation='public.nodes'
union all
select 'public.policy_documents' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(payload order by source_key),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from mip_private.spatial_row_versions where source_project='jfnzyvzthzqtczlxhjll' and source_relation='public.policy_documents'
union all
select 'public.source_change_events' as source_relation,count(*)::text as row_count,encode(sha256(convert_to(coalesce(jsonb_agg(payload order by source_key),'[]'::jsonb)::text,'UTF8')),'hex') as ordered_payload_sha256 from mip_private.spatial_row_versions where source_project='jfnzyvzthzqtczlxhjll' and source_relation='public.source_change_events') x;
select clock_timestamp()::text as observed_at,jsonb_agg(x order by child_relation,child_field,parent_relation) as references from (select 'spatial.assertion_revisions' as child_relation,'canonical_place_id' as child_field,'public.geographic_places' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.geographic_places' and p.source_key=c.payload->>'canonical_place_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.assertion_revisions' and c.payload->>'canonical_place_id' is not null
union all
select 'spatial.assertions' as child_relation,'graph_node_id' as child_field,'public.nodes' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.nodes' and p.source_key=c.payload->>'graph_node_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.assertions' and c.payload->>'graph_node_id' is not null
union all
select 'spatial.evidence_artifact_registry' as child_relation,'article_id' as child_field,'public.articles' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.articles' and p.source_key=c.payload->>'article_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.evidence_artifact_registry' and c.payload->>'article_id' is not null
union all
select 'spatial.evidence_artifact_registry' as child_relation,'policy_document_id' as child_field,'public.policy_documents' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.policy_documents' and p.source_key=c.payload->>'policy_document_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.evidence_artifact_registry' and c.payload->>'policy_document_id' is not null
union all
select 'spatial.evidence_condition_events' as child_relation,'source_change_event_id' as child_field,'public.source_change_events' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.source_change_events' and p.source_key=c.payload->>'source_change_event_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.evidence_condition_events' and c.payload->>'source_change_event_id' is not null
union all
select 'spatial.geometry_snapshots' as child_relation,'canonical_place_id' as child_field,'public.geographic_places' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.geographic_places' and p.source_key=c.payload->>'canonical_place_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.geometry_snapshots' and c.payload->>'canonical_place_id' is not null
union all
select 'spatial.graph_node_authority_snapshots' as child_relation,'graph_node_id' as child_field,'public.nodes' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.nodes' and p.source_key=c.payload->>'graph_node_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.graph_node_authority_snapshots' and c.payload->>'graph_node_id' is not null
union all
select 'spatial.place_authority_snapshots' as child_relation,'canonical_place_id' as child_field,'public.geographic_places' as parent_relation,count(*)::text as referenced_rows,count(*) filter (where not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.geographic_places' and p.source_key=c.payload->>'canonical_place_id'))::text as missing_references from mip_private.spatial_row_versions c where c.source_project='jfnzyvzthzqtczlxhjll' and c.source_relation='spatial.place_authority_snapshots' and c.payload->>'canonical_place_id' is not null) x;

-- Survivor: archive permissions, triggers, constraints and implementation readback.
select clock_timestamp()::text as observed_at,
(select count(*) from mip_private.spatial_row_versions) as archived_versions,
(select relrowsecurity from pg_class where oid='mip_private.spatial_row_versions'::regclass) as rls,
has_table_privilege('anon','mip_private.spatial_row_versions','select') as anon_read,
has_table_privilege('authenticated','mip_private.spatial_row_versions','select') as authenticated_read,
has_function_privilege('anon','mip_private.retain_spatial_rows(text,text,timestamptz,jsonb)','execute') as anon_import,
has_function_privilege('authenticated','mip_private.retain_spatial_rows(text,text,timestamptz,jsonb)','execute') as authenticated_import,
has_table_privilege('service_role','mip_private.spatial_row_versions','select') as worker_read,
has_table_privilege('service_role','mip_private.spatial_row_versions','insert') as worker_insert,
has_table_privilege('service_role','mip_private.spatial_row_versions','update') as worker_update,
has_table_privilege('service_role','mip_private.spatial_row_versions','delete') as worker_delete,
has_table_privilege('service_role','mip_private.spatial_row_versions','truncate') as worker_truncate,
(select jsonb_agg(jsonb_build_object('name',tgname,'enabled',tgenabled,'definition',pg_get_triggerdef(oid)) order by tgname) from pg_trigger where tgrelid='mip_private.spatial_row_versions'::regclass and not tgisinternal) as triggers,
(select jsonb_build_object('security_definer',prosecdef,'config',proconfig,'body',prosrc) from pg_proc where oid='mip_private.retain_spatial_rows(text,text,timestamptz,jsonb)'::regprocedure) as importer;
select clock_timestamp()::text as observed_at,pg_get_functiondef('mip_private.require_spatial_parent_reference()'::regprocedure) as trigger_definition,has_function_privilege('anon','mip_private.require_spatial_parent_reference()','execute') as anon_execute,has_function_privilege('authenticated','mip_private.require_spatial_parent_reference()','execute') as authenticated_execute,(select jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid)) order by conname) from pg_constraint where conrelid='mip_private.spatial_row_versions'::regclass) as constraints;

-- Typed source-record ancestry on the survivor.
select clock_timestamp() as observed_at,
(select count(*) from mip_private.spatial_row_versions c where c.source_relation='spatial.evidence_artifact_registry' and c.payload->>'artifact_type_code'='source_record' and not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.sources' and p.source_key=c.payload->>'source_record_id')) as missing_typed_source,
(select count(*) from mip_private.spatial_row_versions c where c.source_relation='public.sources' and c.payload->>'node_id' is not null and not exists(select 1 from mip_private.spatial_row_versions p where p.source_project=c.source_project and p.source_relation='public.nodes' and p.source_key=c.payload->>'node_id')) as missing_source_node,
(select count(*) from mip_private.spatial_row_versions where source_relation='public.sources' and payload->>'arc_membership_candidate_id' is not null) as source_candidate_references,
(select jsonb_build_object('body',prosrc,'config',proconfig,'security_definer',prosecdef) from pg_proc where oid='mip_private.require_spatial_parent_reference()'::regprocedure) as guard;
