import test from 'node:test'
import assert from 'node:assert/strict'
import { createWorldViewResourceGovernance, WORLD_VIEW_COST_PREFERENCES } from '../src/lib/worldViewResourceGovernance.js'
const authority = () => ({ expiresAt: 1000000, spendingAuthorized: true, monthlyExternalSpentUsd: 0, monthlyExternalReservedUsd: 0, admission: { approved: true }, entitlement: { allowed: true }, budgets: { account: { authoritative:true,remaining:20 }, global:{authoritative:true,remaining:20}, provider:{authoritative:true,remaining:10}, concurrency:{authoritative:true,remaining:2} } })
const setup = () => {let time=0;const g=createWorldViewResourceGovernance({now:()=>time,idleSuspendMs:100,idleDisposeMs:1000});g.setAuthority(authority());g.openSession();g.interact({locationKey:'cleveland'});return {g,advance:n=>time+=n}}
const reserve=(g,id,cost=10)=>g.reserveRequest({id,estimateUsd:cost,quotaUnits:3,authorityReservationId:`server-${id}`})
test('no allowance/preferences imply spending authorization',()=>{const {g}=setup();g.setAuthority({...authority(),spendingAuthorized:false});assert.equal(reserve(g,'a').reason,'spending-not-authorized');assert.equal(WORLD_VIEW_COST_PREFERENCES.spendingAuthorization,false)})
test('pending reservations prevent local parallel oversubscription',()=>{const {g}=setup();assert.equal(reserve(g,'a').allowed,true);assert.equal(reserve(g,'b').allowed,true);assert.equal(reserve(g,'c',0).reason,'concurrency-allowance-exhausted');assert.equal(g.cancelRequest('a'),true);assert.equal(reserve(g,'d').allowed,true)})
test('settled cost cannot reuse stale allowance until server reconciliation',()=>{const {g}=setup();reserve(g,'a',15);g.settleRequest({id:'a',costUsd:15});assert.equal(reserve(g,'b',10).allowed,false);g.setAuthority({...authority(),reconciledReservationIds:['server-a']});assert.equal(reserve(g,'b',10).allowed,true)})
test('hard ceiling includes global external spend and pending cost',()=>{const {g}=setup();g.setAuthority({...authority(),monthlyExternalSpentUsd:195});assert.equal(reserve(g,'a',6).reason,'hard-monthly-cap')})
test('unknown estimates and absent atomic authority reservation fail closed',()=>{const {g}=setup();assert.equal(g.reserveRequest({id:'a',estimateUsd:0}).reason,'atomic-authority-reservation-required');assert.equal(reserve(g,'b',NaN).reason,'estimate-unavailable')})
test('hidden suspends immediately and idle disposes without inventing billing',()=>{const {g,advance}=setup();reserve(g,'a');advance(50);g.transition('hidden');advance(950);g.poll();assert.equal(g.snapshot().disposed,true);assert.equal(g.snapshot().resourceMs,50);assert.equal(g.snapshot().productSessions,1);assert.equal(g.snapshot().distinctLocations,1);assert.equal(g.snapshot().providers.length,0);assert.ok(g.drainEffects().some(e=>e.type==='dispose'))})
test('late receipts survive disposal and cannot be duplicated',()=>{const {g,advance}=setup();reserve(g,'a');advance(1000);g.poll();assert.equal(g.settleRequest({id:'a',provider:'fixture',kind:'tile',transferBytes:12,billableUnits:0,costUsd:0}),true);assert.equal(g.settleRequest({id:'a'}),false);assert.equal(g.snapshot().providerReceipts[0].billableUnits,0)})
test('expiry and idle suspend, interactions never restart resources automatically',()=>{const {g,advance}=setup();g.setAuthority({...authority(),expiresAt:60});reserve(g,'a');advance(60);g.poll();assert.equal(g.snapshot().resource,'fallback');g.interact();assert.equal(g.snapshot().resource,'fallback')})
test('caller mutations and snapshots cannot expand authoritative budgets',()=>{const {g}=setup();const a=authority();g.setAuthority(a);a.budgets.account.remaining=100;assert.equal(reserve(g,'a',21).allowed,false);assert.equal(g.snapshot().authoritativeBudgetEnforcement,false)})
test('authority token cannot be replayed after settlement',()=>{const {g}=setup();reserve(g,'a');g.settleRequest({id:'a',costUsd:1});assert.equal(g.reserveRequest({id:'b',estimateUsd:1,authorityReservationId:'server-a'}).allowed,false)})
test('finite session retention fails closed instead of growing without bound',()=>{const g=createWorldViewResourceGovernance({now:()=>0,maxRequests:1,maxReceipts:1,maxLocations:1});g.setAuthority(authority());g.interact({locationKey:'a'});reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});g.interact({locationKey:'b'});assert.equal(g.snapshot().distinctLocations,null);assert.equal(reserve(g,'b',1).reason,'session-request-capacity')})
test('observed provider units above estimate constrain the next request',()=>{const {g}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1,billableUnits:9});assert.equal(g.snapshot().unreconciledUsage[0].units,9);assert.equal(reserve(g,'b',1).reason,'provider-allowance-exhausted')})
test('disposed authority setter cannot reconcile retained usage',()=>{const {g,advance}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});advance(1000);g.poll();assert.equal(g.setAuthority({...authority(),reconciledReservationIds:['server-a']}),false);assert.equal(g.snapshot().unreconciledUsage.length,1)})
