import test from 'node:test'
import assert from 'node:assert/strict'
import { createWorldViewResourceGovernance, WORLD_VIEW_COST_PREFERENCES } from '../src/lib/worldViewResourceGovernance.js'
const authority = () => ({ expiresAt: 1000000, spendingAuthorized: true, monthlyExternalSpentUsd: 0, monthlyExternalReservedUsd: 0, admission: { approved: true }, entitlement: { allowed: true }, budgets: { account: { authoritative:true,remaining:20 }, global:{authoritative:true,remaining:20}, provider:{authoritative:true,remaining:10}, concurrency:{authoritative:true,remaining:2} } })
const setup = () => {let time=0;const g=createWorldViewResourceGovernance({now:()=>time,idleSuspendMs:100,idleDisposeMs:1000});g.setAuthority(authority());g.openSession();g.interact({locationKey:'cleveland'});return {g,advance:n=>time+=n}}
const reserve=(g,id,cost=10)=>g.reserveRequest({id,estimateUsd:cost,quotaUnits:3,authorityReservationId:`server-${id}`})
test('no allowance/preferences imply spending authorization',()=>{const {g}=setup();g.setAuthority({...authority(),spendingAuthorized:false});assert.equal(reserve(g,'a').reason,'spending-not-authorized');assert.equal(WORLD_VIEW_COST_PREFERENCES.spendingAuthorization,false)})
test('pending reservations prevent local parallel oversubscription',()=>{const {g}=setup();assert.equal(reserve(g,'a').allowed,true);assert.equal(reserve(g,'b').allowed,true);assert.equal(reserve(g,'c',0).reason,'concurrency-allowance-exhausted');assert.equal(g.cancelRequest('a'),true);assert.equal(reserve(g,'d').allowed,true)})
test('settled cost cannot reuse stale allowance until server reconciliation',()=>{const {g}=setup();reserve(g,'a',15);g.settleRequest({id:'a',costUsd:15});assert.equal(reserve(g,'b',10).allowed,false);g.setAuthority({...authority(),reconciledReservationIds:['server-a']});assert.equal(reserve(g,'b',10).allowed,true)})
test('hard ceiling includes global external spend and pending cost',()=>{const {g}=setup();g.setAuthority({...authority(),monthlyExternalSpentUsd:195});assert.equal(reserve(g,'a',6).reason,'hard-monthly-cap')})
test('unknown estimates and absent atomic authority reservation fail closed',()=>{const {g}=setup();assert.equal(g.reserveRequest({id:'a',estimateUsd:0}).reason,'atomic-authority-reservation-required');assert.equal(reserve(g,'b',NaN).reason,'estimate-unavailable')})
test('hidden suspends immediately and idle disposes without inventing billing',()=>{const {g,advance}=setup();reserve(g,'a');advance(50);g.transition('hidden');advance(950);g.poll();assert.equal(g.snapshot().disposed,true);assert.equal(g.snapshot().resourceMs,50);assert.equal(g.snapshot().productSessions,1);assert.equal(g.snapshot().distinctLocations,1);assert.equal(g.snapshot().providers.length,0);assert.ok(g.drainEffects().some(e=>e.type==='dispose'))})
test('late receipts survive disposal and cannot be duplicated',()=>{const {g,advance}=setup();reserve(g,'a');advance(1000);g.poll();assert.equal(g.settleRequest({id:'a',provider:'fixture',kind:'tile',transferBytes:12,billableUnits:0,costUsd:0}),true);assert.equal(g.settleRequest({id:'a'}),false);assert.equal(g.snapshot().providerReceipts[0].billableUnits,0)})
test('expiry and idle suspend, interactions never restart resources automatically',()=>{const {g,advance}=setup();g.setAuthority({...authority(),expiresAt:60});reserve(g,'a');advance(60);g.poll();assert.equal(g.snapshot().resource,'fallback');g.interact();assert.equal(g.snapshot().resource,'fallback')})
test('caller mutations and snapshots cannot expand authoritative budgets',()=>{const {g}=setup();const a=authority();g.setAuthority(a);a.budgets.account.remaining=100;assert.equal(reserve(g,'a',21).allowed,false);assert.equal(g.snapshot().authoritativeBudgetEnforcement,false)})
test('authority token cannot be replayed after settlement',()=>{const {g}=setup();reserve(g,'a');g.settleRequest({id:'a',costUsd:1});assert.equal(g.reserveRequest({id:'b',estimateUsd:1,authorityReservationId:'server-a'}).allowed,false)})
test('finite session retention fails closed instead of growing without bound',()=>{const g=createWorldViewResourceGovernance({now:()=>0,maxRequests:1,maxReceipts:1,maxLocations:1});g.setAuthority(authority());g.interact({locationKey:'a'});reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});g.interact({locationKey:'b'});assert.equal(g.snapshot().distinctLocations,null);assert.equal(reserve(g,'b',1).reason,'session-request-capacity')})
test('observed provider units above estimate constrain the next request',()=>{const {g}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1,billableUnits:9});assert.equal(g.snapshot().unreconciledUsage[0].units,9);assert.equal(reserve(g,'b',1).reason,'provider-allowance-exhausted')})
test('disposed authority setter cannot reconcile retained usage',()=>{const {g,advance}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});advance(1000);g.poll();assert.equal(g.setAuthority({...authority(),reconciledReservationIds:['server-a']}),false);assert.equal(g.snapshot().unreconciledUsage.length,1)})
test('late unknown-to-known corrections are revision-idempotent and leave request telemetry count unchanged',()=>{
 const {g}=setup();reserve(g,'a',1);g.settleRequest({id:'a',provider:'fixture',kind:'tile'})
 assert.equal(g.snapshot().unknownCostReceipts,1)
 assert.equal(g.correctObservation({id:'a',revision:1,transferBytes:12,billableUnits:4,costUsd:2}).accepted,true)
 assert.equal(g.correctObservation({id:'a',revision:1,transferBytes:100,costUsd:20}).accepted,false)
 assert.equal(g.correctObservation({id:'a',revision:0,costUsd:20}).reason,'duplicate-or-out-of-order-observation')
 assert.equal(g.correctObservation({id:'a',revision:2,transferBytes:10,billableUnits:2,costUsd:1}).accepted,true)
 const state=g.snapshot();assert.equal(state.observedRequests,1);assert.equal(state.observableBytes,0);assert.equal(state.unknownCostReceipts,0)
 assert.deepEqual(state.unreconciledUsage,[{usd:2,units:4,slots:0}]);assert.equal(state.observationCorrections.bytes,12);assert.equal(state.observationCorrections.units,4);assert.equal(state.observationCorrections.usd,2)
 assert.equal(g.correctObservation({id:'a',revision:1,costUsd:10}).reason,'duplicate-or-out-of-order-observation')
 assert.equal(g.snapshot().observationCorrections.usd,2)
})
test('corrected overruns constrain admission without a second release or fabricated authority',()=>{
 const {g}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1,billableUnits:3});g.drainEffects()
 assert.equal(g.correctObservation({id:'a',revision:1,billableUnits:11,costUsd:21}).accepted,true)
 const effects=g.drainEffects();assert.equal(effects.filter(e=>e.type==='release-reservation').length,0);assert.equal(effects.find(e=>e.type==='observation-corrected').overEstimate,true)
 assert.equal(reserve(g,'b',0).allowed,false);assert.equal(g.snapshot().authoritativeBudgetEnforcement,false)
})
test('corrections after authority reconciliation add only conservative excess over reconciled baseline',()=>{
 const {g}=setup();reserve(g,'a',5);g.settleRequest({id:'a',costUsd:2,billableUnits:2})
 g.setAuthority({...authority(),reconciledReservationIds:['server-a']});assert.deepEqual(g.snapshot().unreconciledUsage,[])
 g.correctObservation({id:'a',revision:1,costUsd:4,billableUnits:3});assert.deepEqual(g.snapshot().unreconciledUsage,[])
 g.correctObservation({id:'a',revision:2,costUsd:8,billableUnits:5});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:3,units:2,slots:0}])
 g.setAuthority({...authority(),reconciledReservationIds:['server-a']});g.correctObservation({id:'a',revision:3,costUsd:9,billableUnits:6});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:4,units:3,slots:0}])
})
test('canceled late observation remains correctable after disposal without re-releasing slots',()=>{
 const {g,advance}=setup();reserve(g,'a',10);assert.equal(g.cancelRequest('a'),true);assert.deepEqual(g.snapshot().unreconciledUsage,[]);assert.equal(g.cancelRequest('a'),false);g.drainEffects()
 advance(1000);g.poll();g.drainEffects()
 assert.equal(g.correctObservation({id:'a',revision:1,transferBytes:30,billableUnits:2,costUsd:4}).accepted,true)
 assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:4,units:2,slots:0}]);assert.equal(g.snapshot().pendingRequests,0);assert.equal(g.snapshot().disposed,true);assert.equal(g.snapshot().resource,'fallback');assert.equal(g.snapshot().providers.length,0)
 assert.equal(g.drainEffects().filter(e=>e.type==='release-reservation').length,0)
 g.correctObservation({id:'a',revision:2,costUsd:2});assert.equal(g.snapshot().unreconciledUsage[0].usd,4)
})
test('bounded receipt identities reject evicted and unknown corrections and latch admission fallback',()=>{
 const g=createWorldViewResourceGovernance({now:()=>0,maxReceipts:1});g.setAuthority(authority());g.interact()
 reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});reserve(g,'b',1);g.cancelRequest('b')
 assert.equal(g.snapshot().providerReceipts.length,1);assert.equal(g.snapshot().observationCorrections.retainedIdentities,1)
 assert.equal(g.correctObservation({id:'a',revision:1,costUsd:2}).reason,'observation-identity-unavailable')
 assert.equal(reserve(g,'c',1).reason,'observation-identity-unavailable');g.setAuthority(authority());assert.equal(reserve(g,'d',1).allowed,false)
 assert.equal(g.correctObservation({id:'not-reserved',revision:1,costUsd:3}).accepted,false);assert.equal(g.snapshot().observationCorrections.usd,1)
 assert.equal(g.correctObservation({id:'b',revision:1,costUsd:2}).accepted,true);assert.equal(g.snapshot().observationCorrections.usd,3)
})
test('invalid correction revisions and values cannot mutate retained observations',()=>{
 const {g}=setup();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1})
 for(const value of [{revision:NaN},{revision:1.5},{revision:Number.MAX_SAFE_INTEGER+1},{revision:1,costUsd:-1},{revision:1,transferBytes:Infinity}])assert.equal(g.correctObservation({id:'a',...value}).reason,'invalid-observation')
 assert.equal(g.snapshot().providerReceipts[0].revision,0);assert.equal(g.snapshot().observationCorrections.corrections,0);assert.equal(g.snapshot().observationCorrections.identityUnavailable,false)
 const state=g.snapshot();state.providerReceipts[0].costUsd=100;state.observationCorrections.usd=100;assert.equal(g.snapshot().observationCorrections.usd,1)
})
test('disposed settlement correction records actual maxima and keeps frozen provider telemetry',()=>{
 const {g,advance}=setup();reserve(g,'a',1);g.settleRequest({id:'a',provider:'fixture',kind:'tile'});const initial=g.snapshot().providers
 advance(1000);g.poll()
 g.correctObservation({id:'a',revision:1,provider:'swapped',kind:'other',transferBytes:0,billableUnits:0,costUsd:0})
 assert.equal(g.snapshot().providerReceipts[0].provider,'fixture');assert.equal(g.snapshot().providerReceipts[0].kind,'tile');assert.equal(g.snapshot().unknownCostReceipts,0);assert.deepEqual(g.snapshot().providers,initial)
 g.correctObservation({id:'a',revision:2,transferBytes:40,billableUnits:7,costUsd:8});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:8,units:7,slots:0}]);assert.equal(g.snapshot().observationCorrections.bytes,40)
 g.correctObservation({id:'a',revision:1,transferBytes:400,costUsd:80});assert.equal(g.snapshot().observationCorrections.usd,8)
})
test('repeated corrections retain bounded identity and notification state',()=>{
 const g=createWorldViewResourceGovernance({now:()=>0,maxReceipts:1});g.setAuthority(authority());g.interact();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1})
 for(let revision=1;revision<=100;revision++)g.correctObservation({id:'a',revision,transferBytes:revision})
 assert.equal(g.snapshot().observationCorrections.retainedIdentities,1);assert.equal(g.snapshot().observationCorrections.bytes,100);const corrections=g.drainEffects().filter(e=>e.type==='observation-corrected');assert.equal(corrections.length,1);assert.equal(corrections[0].observedTotals.transferBytes,100)
})
test('unchanged reconciliation grant cannot erase later correction excess',()=>{
 const {g}=setup();reserve(g,'a',5);g.settleRequest({id:'a',costUsd:5,billableUnits:3});const grant={...authority(),reconciledReservationIds:['server-a']}
 g.setAuthority(grant);g.correctObservation({id:'a',revision:1,costUsd:15,billableUnits:8})
 g.setAuthority(grant);assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:10,units:5,slots:0}])
 g.setAuthority({...grant,monthlyExternalSpentUsd:5});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:10,units:5,slots:0}])
 g.correctObservation({id:'a',revision:2,costUsd:17,billableUnits:9});g.setAuthority(grant);assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:12,units:6,slots:0}])
})
test('first ID-only reconciliation acknowledges original settlement, never preceding corrections',()=>{
 const {g}=setup();reserve(g,'a',5);g.settleRequest({id:'a',costUsd:5,billableUnits:3});g.correctObservation({id:'a',revision:1,costUsd:15,billableUnits:8})
 g.setAuthority({...authority(),reconciledReservationIds:['server-a']});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:10,units:5,slots:0}])
 const canceled=setup().g;reserve(canceled,'a',5);canceled.cancelRequest('a');canceled.correctObservation({id:'a',revision:1,costUsd:15,billableUnits:8});canceled.setAuthority({...authority(),reconciledReservationIds:['server-a']})
 assert.deepEqual(canceled.snapshot().unreconciledUsage,[{usd:15,units:8,slots:0}])
})
test('evicted corrected baseline stays held and premature pending acknowledgment cannot poison final reconciliation',()=>{
 const g=createWorldViewResourceGovernance({now:()=>0,maxReceipts:1});g.setAuthority(authority());g.interact();reserve(g,'a',1);g.settleRequest({id:'a',costUsd:1});g.correctObservation({id:'a',revision:1,costUsd:4});reserve(g,'b',1);g.cancelRequest('b')
 g.setAuthority({...authority(),reconciledReservationIds:['server-a']});assert.deepEqual(g.snapshot().unreconciledUsage,[{usd:4,units:3,slots:0}])
 const pending=setup().g;reserve(pending,'a',1);pending.setAuthority({...authority(),reconciledReservationIds:['server-a']});pending.settleRequest({id:'a',costUsd:1});pending.correctObservation({id:'a',revision:1,costUsd:4});pending.setAuthority({...authority(),reconciledReservationIds:['server-a']})
 assert.deepEqual(pending.snapshot().unreconciledUsage,[{usd:3,units:0,slots:0}])
})
