-- READ ONLY. Pin complete canonical installed catalog separately for rollback.
begin read only;
set local search_path=pg_catalog;
with names as (
 select distinct p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='evidence_pipeline' or (n.nspname='public' and p.proname like 'mip\_%' escape '\')
 union select unnest(array['selective_metadata_decision','mip_selective_execution_v1'])
), targets as (select unnest(array['selective_criteria_versions','selective_source_authorizations','selective_authorization_revocations','selective_discovery_receipts','selective_fetch_permits','selective_execution_receipts','_selective_criteria_versions','_selective_source_authorizations','_selective_authorization_revocations','_selective_discovery_receipts','_selective_fetch_permits','_selective_execution_receipts','selective_criteria_versions_pkey','selective_source_authorizations_pkey','selective_authorization_revocations_pkey','selective_discovery_receipts_pkey','selective_fetch_permits_pkey','selective_execution_receipts_pkey','selective_discovery_receipts_ordinal_seq','selective_execution_receipts_ordinal_seq','selective_discovery_receipts_ordinal_key','selective_execution_receipts_ordinal_key','selective_discovery_head','selective_fetch_permits_selection_id_key','selective_execution_receipts_previous_execution_id_key','selective_execution_receipts_declaration_receipt_id_key','selective_execution_receipts_reconsideration_receipt_id_key']) name)
select jsonb_build_object(
 'database',current_database(),'server_version_num',current_setting('server_version_num'),'installer',current_user,
 'schemas',(select jsonb_agg(jsonb_build_object('name',n.nspname,'owner',pg_get_userbyid(n.nspowner),'acl',(select coalesce(jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(z.grantor),'grantee',case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,'privilege',z.privilege_type,'grantable',z.is_grantable) order by pg_get_userbyid(z.grantor),case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,z.privilege_type,z.is_grantable),'[]') from aclexplode(coalesce(n.nspacl,acldefault('n',n.nspowner)))z)) order by n.nspname) from pg_namespace n where n.nspname not like 'pg_%' and n.nspname<>'information_schema'),
 'default_acls',(select coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',coalesce(n.nspname,'GLOBAL'),'kind',d.defaclobjtype,'acl',(select coalesce(jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(z.grantor),'grantee',case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,'privilege',z.privilege_type,'grantable',z.is_grantable) order by pg_get_userbyid(z.grantor),case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,z.privilege_type,z.is_grantable),'[]') from aclexplode(d.defaclacl)z)) order by pg_get_userbyid(d.defaclrole),coalesce(n.nspname,'GLOBAL'),d.defaclobjtype),'[]') from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace),
 'relations',(select jsonb_agg(jsonb_build_object('identity',c.oid::regclass::text,'owner',pg_get_userbyid(c.relowner),'kind',c.relkind,'acl',(select coalesce(jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(z.grantor),'grantee',case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,'privilege',z.privilege_type,'grantable',z.is_grantable) order by pg_get_userbyid(z.grantor),case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,z.privilege_type,z.is_grantable),'[]') from aclexplode(coalesce(c.relacl,acldefault(case when c.relkind='S' then 'S'::"char" else 'r'::"char" end,c.relowner)))z),
  'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'options',c.reloptions,'definition',case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) when c.relkind in ('i','I') then pg_get_indexdef(c.oid) else null end,
  'columns',(select coalesce(jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'acl',(select coalesce(jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(z.grantor),'grantee',case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,'privilege',z.privilege_type,'grantable',z.is_grantable) order by pg_get_userbyid(z.grantor),case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,z.privilege_type,z.is_grantable),'[]') from aclexplode(a.attacl)z)) order by a.attnum),'[]') from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
  'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',x.conname,'definition',pg_get_constraintdef(x.oid)) order by x.conname),'[]') from pg_constraint x where x.conrelid=c.oid),
  'policies',(select coalesce(jsonb_agg(jsonb_build_object('name',p.polname,'cmd',p.polcmd,'permissive',p.polpermissive,'roles',(select jsonb_agg(case when r=0 then 'PUBLIC' else pg_get_userbyid(r) end order by case when r=0 then 'PUBLIC' else pg_get_userbyid(r) end) from unnest(p.polroles)r),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid)) order by p.polname),'[]') from pg_policy p where p.polrelid=c.oid),
  'triggers',(select coalesce(jsonb_agg(jsonb_build_object('name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid),'function',pg_get_functiondef(t.tgfoid)) order by t.tgname),'[]') from pg_trigger t where t.tgrelid=c.oid and not t.tgisinternal),
  'sequence',case when c.relkind='S' then (select jsonb_build_object('type',format_type(seq.seqtypid,null),'start',seq.seqstart::text,'increment',seq.seqincrement::text,'min',seq.seqmin::text,'max',seq.seqmax::text,'cache',seq.seqcache::text,'cycle',seq.seqcycle) from pg_sequence seq where seq.seqrelid=c.oid) else null end) order by c.oid::regclass::text)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='evidence_pipeline' or (n.nspname='public' and c.relname in ('articles','nodes','pipeline_config','geographic_places','mip_profiles'))),
 'functions',(select coalesce(jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'schema',n.nspname,'owner',pg_get_userbyid(p.proowner),'acl',(select coalesce(jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(z.grantor),'grantee',case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,'privilege',z.privilege_type,'grantable',z.is_grantable) order by pg_get_userbyid(z.grantor),case when z.grantee=0 then 'PUBLIC' else pg_get_userbyid(z.grantee) end,z.privilege_type,z.is_grantable),'[]') from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))z),'definition',pg_get_functiondef(p.oid)) order by p.oid::regprocedure::text),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in (select proname from names)),
 'roles',(select jsonb_agg(jsonb_build_object('name',r.rolname,'login',r.rolcanlogin,'inherit',r.rolinherit,'superuser',r.rolsuper,'bypass_rls',r.rolbypassrls,'create_role',r.rolcreaterole,'create_db',r.rolcreatedb,'replication',r.rolreplication,'connection_limit',r.rolconnlimit,'valid_until_epoch',extract(epoch from r.rolvaliduntil)::text,'config',r.rolconfig,
  'memberships',(select coalesce(jsonb_agg(jsonb_build_object('role',pg_get_userbyid(m.roleid),'grantor',pg_get_userbyid(m.grantor),'admin',m.admin_option,'inherit',to_jsonb(m)->'inherit_option','set',to_jsonb(m)->'set_option') order by pg_get_userbyid(m.roleid),pg_get_userbyid(m.grantor)),'[]') from pg_auth_members m where m.member=r.oid)) order by r.rolname) from pg_roles r),
 'target_relations',(select coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner)) order by c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='evidence_pipeline' and c.relname in (select name from targets)),
 'target_types',(select coalesce(jsonb_agg(jsonb_build_object('name',t.typname,'kind',t.typtype,'owner',pg_get_userbyid(t.typowner)) order by t.typname),'[]') from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='evidence_pipeline' and t.typname in (select name from targets)),
 'target_signatures',jsonb_build_array(to_regprocedure('evidence_pipeline.selective_metadata_decision(jsonb,jsonb)')::text,to_regprocedure('public.mip_selective_execution_v1(text,jsonb)')::text)
) ;
rollback;
