import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { createPreview } from './demoCorpus.mjs'
import receipts from '../verifier/demo-corpus-20260916/retained-source-receipts.json'
import expandedReceipts from '../verifier/demo-corpus-20260916/expanded-source-receipts.json'
import './demo-corpus-preview.css'

const investigations = createPreview([...receipts, ...expandedReceipts])
const topicMeta = {
  iran: { name: 'US–Iran', kicker: 'Conflict, diplomacy & oversight', color: '#d7aa65' },
  epstein: { name: 'Epstein disclosure', kicker: 'Disclosure & oversight', color: '#a699e8' },
  project2025: { name: 'Project 2025', kicker: 'Proposals, actions & review', color: '#72c7ad' },
}
const surfaces = [['context', 'Context'], ['news', 'Sources'], ['evidence', 'Evidence'], ['compare', 'Compare'], ['graph', 'Graph'], ['timeline', 'Timeline'], ['arc', 'Research Arc']]

function parseRoute() {
  const [, root, topic, surface, capture] = window.location.hash.split('/')
  return { topic: root === 'demo' && topicMeta[topic] ? topic : 'iran', surface: root === 'demo' && surfaces.some(([key]) => key === surface) ? surface : 'context', capture: capture ? decodeURIComponent(capture) : null }
}
function sanitizeRoute(route) {
  if (!route.capture) return route
  const collection = investigations.find((item) => item.topic === route.topic)
  return collection.sources.some((source) => source.capture_id === route.capture) ? route : { ...route, surface: 'context', capture: null }
}
function writeRoute(topic, surface, capture = null) { const next = `#/demo/${topic}/${surface}${capture ? `/${encodeURIComponent(capture)}` : ''}`; if (window.location.hash !== next) window.location.hash = next }
const shortId = (value) => value ? `${value.slice(0, 8)}…${value.slice(-4)}` : '—'
const pretty = (value) => String(value ?? 'unresolved').replaceAll('_', ' ')
function StatusPill({ children, tone = 'pending' }) { return <span className={`status status--${tone}`}>{children}</span> }

function SourceCard({ source, selected, onSelect, compact = false }) {
  return <button className={`source-card${selected ? ' source-card--selected' : ''}${compact ? ' source-card--compact' : ''}`} onClick={() => onSelect(source)}>
    <div className="source-card__meta"><span>{source.outlet}</span><time>{source.source_date ?? 'Date unresolved'}</time></div><h3>{source.title}</h3>{!compact && <p>{source.statement}</p>}
    <div className="source-card__footer"><span>{pretty(source.semantic_kind)}</span><span>capture {shortId(source.capture_id)}</span></div>
  </button>
}

function ProvenanceInspector({ source, onClose }) {
  return <aside className={`inspector${source ? ' inspector--open' : ''}`} aria-label="Provenance inspector"><div className="inspector__head"><span className="eyebrow">PROVENANCE</span>{source && <button onClick={onClose} aria-label="Close inspector">×</button>}</div>{source ? <>
    <StatusPill>pending review · private</StatusPill><h2>{source.title}</h2><p className="inspector__statement">Synopsis: {source.statement}</p>
    <section className="evidence-frame"><span>Exact retained evidence identity</span><strong>Code points {source.span_start ?? '?'}–{source.span_end ?? '?'}</strong><p>The bounded text is held in the private capture. This metadata-only demo does not reproduce it; the hash and offsets identify the exact retained version.</p></section>
    <dl className="provenance-grid"><dt>Capture</dt><dd>{source.capture_id}</dd><dt>Article</dt><dd>{source.article_id}</dd><dt>Candidate</dt><dd>{source.candidate_id ?? 'None'}</dd><dt>SHA-256</dt><dd>{source.content_hash}</dd><dt>Origin</dt><dd>{source.origin_id ?? 'Unresolved'}</dd><dt>Dependency</dt><dd>{source.dependency_id ?? 'Unresolved'}</dd><dt>Source date</dt><dd>{source.source_date ?? 'Unresolved'} · {source.publication_precision}</dd><dt>Retention</dt><dd>{source.retained_scope}</dd><dt>Rights collection note</dt><dd>{source.rights}</dd></dl>
    <section className="uncertainty"><span>Remaining uncertainty</span><p>{source.remaining_uncertainty}</p></section><a className="source-link" href={source.url} target="_blank" rel="noreferrer">Open original source ↗</a>
  </> : <div className="inspector__empty"><div className="fingerprint">⌁</div><h2>Inspect the chain</h2><p>Select any source or pending statement to see its capture, candidate, span, hash, dependency and uncertainty.</p></div>}</aside>
}

function ContextView({ investigation, topic, openSurface }) {
  const meta = topicMeta[topic], dated = investigation.sources.filter((s) => s.source_date).map((s) => s.source_date).sort(), kinds = [...new Set(investigation.sources.map((s) => s.semantic_kind))]
  return <div className="context-view"><section className="context-hero" style={{ '--accent': meta.color }}><div><span className="eyebrow">PRIVATE INVESTIGATION · DEMONSTRATION</span><h1>{meta.name}</h1><p>{meta.kicker}</p></div><StatusPill>not admitted</StatusPill></section>
    <div className="metric-row"><div><strong>{investigation.sources.length}</strong><span>retained captures</span></div><div><strong>{investigation.accounting.independent_origins}</strong><span>declared origins</span></div><div><strong>{investigation.dependencyGroups.length}</strong><span>dependency groups</span></div><div><strong>0</strong><span>public nodes created</span></div></div>
    <section className="context-grid"><article className="panel panel--large"><span className="eyebrow">INVESTIGATION BOUNDARY</span><h2>Evidence before admission</h2><p>This collection joins retained source metadata, immutable private capture identities and pending exact-span candidates. It is a research workspace—not accepted knowledge, a public narrative, or a publication surface.</p><div className="guardrail-list"><span>Candidate ≠ accepted claim</span><span>Publication date ≠ event time</span><span>Co-mention ≠ relationship</span><span>Repetition ≠ corroboration</span></div></article><article className="panel"><span className="eyebrow">COVERAGE WINDOW</span><strong className="panel__value">{dated[0]} → {dated.at(-1)}</strong><p>Source/document publication dates only.</p></article><article className="panel"><span className="eyebrow">EVIDENCE SHAPES</span><strong className="panel__value">{kinds.length}</strong><p>{kinds.slice(0, 4).map(pretty).join(' · ')}{kinds.length > 4 ? ' …' : ''}</p></article></section>
    <div className="launch-row"><button onClick={() => openSurface('news')}>Browse retained sources <span>→</span></button><button onClick={() => openSurface('timeline')}>View publication timeline <span>→</span></button><button onClick={() => openSurface('graph')}>Inspect attribution graph <span>→</span></button></div></div>
}

function SourcesView({ investigation, query, onSelect }) {
  const needle = query.trim().toLowerCase(), rows = investigation.sources.filter((s) => !needle || [s.title, s.outlet, s.statement, s.semantic_kind].some((v) => String(v ?? '').toLowerCase().includes(needle)))
  return <section><div className="surface-title"><div><span className="eyebrow">RETAINED SOURCE REGISTER</span><h1>{rows.length} source{rows.length === 1 ? '' : 's'}</h1></div><p>Private captures · pending review · no publication control</p></div><div className="source-list">{rows.map((s) => <SourceCard key={s.capture_id} source={s} onSelect={onSelect} />)}</div>{rows.length === 0 && <div className="honest-empty"><h2>No matching retained sources</h2><p>Search does not query or mutate the production corpus.</p></div>}</section>
}
function EvidenceView({ investigation, onSelect }) { return <section><div className="surface-title"><div><span className="eyebrow">EXACT-SPAN CANDIDATES</span><h1>Evidence ledger</h1></div><p>Every row preserves one capture → candidate identity</p></div><div className="ledger"><div className="ledger__header"><span>Source / synopsis</span><span>Exact span</span><span>State</span><span>Identity</span></div>{investigation.sources.map((s) => <button key={s.candidate_id} onClick={() => onSelect(s)}><span><strong>{s.title}</strong><small>{s.statement}</small></span><span>{s.span_start}–{s.span_end}</span><span><StatusPill>{s.candidate_state}</StatusPill></span><span>{shortId(s.candidate_id)}</span></button>)}</div></section> }
function CompareView({ investigation, onSelect }) { const grouped = investigation.dependencyGroups.filter((g) => g.members.length > 1), byCapture = new Map(investigation.sources.map((s) => [s.preview_id, s])); return <section><div className="surface-title"><div><span className="eyebrow">SOURCE COMPARISON</span><h1>Declared dependencies</h1></div><p>No common event identity has been admitted</p></div><div className="boundary-note"><strong>Comparison is intentionally conservative.</strong><span>A shared topic or institution does not establish event equivalence or independent corroboration. Only receipt-declared dependency groups are paired.</span></div><div className="comparison-grid">{grouped.map((g) => <article className="comparison-group" key={g.id}><header><span>{g.id}</span><StatusPill tone="neutral">dependent material</StatusPill></header>{g.members.map((id) => <SourceCard compact key={id} source={byCapture.get(id)} onSelect={onSelect} />)}</article>)}</div>{grouped.length === 0 && <div className="honest-empty"><h2>No defensible comparison pair</h2><p>The sources remain available individually; the demo does not manufacture a comparison event.</p></div>}</section> }
function GraphView({ investigation, onSelect }) { const originMap = new Map(investigation.origins.map((o) => [o.id, o])), sourcesByOrigin = new Map(); for (const source of investigation.sources) { const key = source.origin_id ? `private:origin:${source.origin_id}` : 'private:origin:unresolved'; sourcesByOrigin.set(key, [...(sourcesByOrigin.get(key) ?? []), source]) } return <section><div className="surface-title"><div><span className="eyebrow">ATTRIBUTION-SAFE GRAPH</span><h1>Source lineage</h1></div><p>Origins → captures → pending statements</p></div><div className="boundary-note"><strong>No actor or causal edges.</strong><span>These links describe evidence custody and attribution only. They do not assert persistent real-world relationships.</span></div><div className="graph-board">{[...sourcesByOrigin].map(([id, rows], index) => <article className="origin-lane" key={id} style={{ '--lane': index % 5 }}><header><span className="origin-dot"/><div><small>PROVENANCE SOURCE GROUP</small><h2>{originMap.get(id)?.label ?? 'Origin unresolved'}</h2></div><strong>{rows.length}</strong></header><div className="origin-sources">{rows.map((s) => <button key={s.capture_id} onClick={() => onSelect(s)}><span className="line"/><span>{s.statement}</span><small>{shortId(s.capture_id)} · pending</small></button>)}</div></article>)}</div></section> }
function TimelineView({ investigation, onSelect }) { const groups = Map.groupBy([...investigation.sources].sort((a, b) => (a.source_date ?? '9999').localeCompare(b.source_date ?? '9999')), (s) => `${s.source_date ?? 'Date unresolved'}|${s.publication_precision}`); return <section><div className="surface-title"><div><span className="eyebrow">DOCUMENT CHRONOLOGY</span><h1>Publication timeline</h1></div><p>Publication basis only · not inferred event time</p></div><div className="boundary-note"><strong>Temporal basis: source date.</strong><span>Placement means the document was dated here. It does not assert when the described conduct or event occurred.</span></div><div className="timeline">{[...groups].map(([key, rows]) => { const [date, precision] = key.split('|'); return <section key={key}><time>{date}<small>{precision}</small></time><div>{rows.map((s) => <SourceCard compact key={s.capture_id} source={s} onSelect={onSelect} />)}</div></section> })}</div></section> }
function ArcView({ investigation, topic, onSelect }) { return <section><div className="surface-title"><div><span className="eyebrow">RESEARCH COLLECTION</span><h1>{topicMeta[topic].name}</h1></div><p>Membership, not an approved narrative arc</p></div><article className="arc-card"><header><div><span className="eyebrow">COLLECTION ID</span><code>{investigation.arc.id}</code></div><StatusPill>{investigation.sources.length} pending members</StatusPill></header><div className="arc-thread">{investigation.sources.map((s, i) => <button key={s.capture_id} onClick={() => onSelect(s)}><span>{String(i + 1).padStart(2, '0')}</span><div><strong>{s.title}</strong><small>{s.outlet} · {s.source_date ?? 'date unresolved'}</small></div></button>)}</div></article></section> }

function DemoApp() {
  const initial = sanitizeRoute(parseRoute()), [topic, setTopic] = useState(initial.topic), [surface, setSurface] = useState(initial.surface), [selectedId, setSelectedId] = useState(initial.capture), [query, setQuery] = useState('')
  const investigation = investigations.find((i) => i.topic === topic), selected = investigation.sources.find((s) => s.capture_id === selectedId) ?? null
  useEffect(() => { const update = () => { const parsed = parseRoute(), route = sanitizeRoute(parsed); if (route.surface !== parsed.surface || route.capture !== parsed.capture) { writeRoute(route.topic, route.surface); return } setTopic(route.topic); setSurface(route.surface); setSelectedId(route.capture) }; window.addEventListener('hashchange', update); if (!window.location.hash) writeRoute(topic, surface); else if (initial.capture !== parseRoute().capture) writeRoute(initial.topic, initial.surface); return () => window.removeEventListener('hashchange', update) }, [])
  const selectTopic = (next) => writeRoute(next, 'context'), openSurface = (next) => writeRoute(topic, next, selectedId), selectSource = (source) => writeRoute(topic, surface, source.capture_id)
  const view = useMemo(() => ({ context: <ContextView investigation={investigation} topic={topic} openSurface={openSurface} />, news: <SourcesView investigation={investigation} query={query} onSelect={selectSource} />, evidence: <EvidenceView investigation={investigation} onSelect={selectSource} />, compare: <CompareView investigation={investigation} onSelect={selectSource} />, graph: <GraphView investigation={investigation} onSelect={selectSource} />, timeline: <TimelineView investigation={investigation} onSelect={selectSource} />, arc: <ArcView investigation={investigation} topic={topic} onSelect={selectSource} /> })[surface], [investigation, query, surface, topic, selectedId])
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand__mark">M</span><div><strong>Media Intelligence Platform</strong><small>PRIVATE DEMONSTRATION WORKSPACE</small></div></div><div className="topbar__state"><span>93 retained sources</span><StatusPill>all pending</StatusPill></div></header><div className="demo-banner"><strong>DEMO / NONCANONICAL</strong><span>No record shown here is public, admitted, or available to production write paths.</span></div><div className="shell-body">
    <nav className="sidebar" aria-label="Investigation navigation"><span className="eyebrow">INVESTIGATIONS</span>{investigations.map((item) => <button key={item.topic} onClick={() => selectTopic(item.topic)} aria-current={item.topic === topic ? 'page' : undefined}><span className="topic-dot" style={{ background: topicMeta[item.topic].color }}/><span><strong>{topicMeta[item.topic].name}</strong><small>{item.sources.length} retained</small></span></button>)}<div className="sidebar__rule"/><span className="eyebrow">SURFACES</span>{surfaces.map(([key, label]) => <button className="surface-nav" key={key} onClick={() => openSurface(key)} aria-current={surface === key ? 'page' : undefined}><span>{label}</span><small>→</small></button>)}<div className="withheld"><span>World View</span><small>withheld · no reviewed geography</small></div></nav>
    <main className="main-column"><div className="workspace-bar"><span className="breadcrumb">Investigations / {topicMeta[topic].name} / {surfaces.find(([key]) => key === surface)?.[1]}</span><label className="search"><span>⌕</span><input value={query} onChange={(e) => { setQuery(e.target.value); if (surface !== 'news') writeRoute(topic, 'news') }} placeholder="Search retained sources" aria-label="Search retained sources"/></label></div><div className="view-scroll">{view}</div></main><ProvenanceInspector source={selected} onClose={() => writeRoute(topic, surface)} /></div></div>
}
createRoot(document.getElementById('root')).render(<DemoApp />)
