// AUTO-DERIVED from live V2 canonical signatures (pg_proc, 2026-09-01) + owner ruling on
// append_evidence_snapshot.p_content_hash. Do not hand-edit; regenerate from the matrix.
export type ParamKind = "client" | "canon" | "hash" | "run";
export interface ParamSpec {
  name: string;
  kind: ParamKind;
  key?: string;
  type?: "text" | "uuid" | "jsonb" | "integer" | "timestamptz" | "sha256hex";
  required?: boolean;
  of?: string;
}
export interface OperationSpec {
  fn: string;
  arity: number;
  params: readonly ParamSpec[];
  primary: string;
}
export const OPERATIONS = {
  append_policy_artifact: {
    fn: "spatial.append_policy_artifact",
    arity: 8,
    primary: "p_content_hash",
    params: [
      {
        name: "p_policy_family_code",
        kind: "client",
        key: "policy_family_code",
        type: "text",
        required: true,
      },
      {
        name: "p_policy_version",
        kind: "client",
        key: "policy_version",
        type: "text",
        required: true,
      },
      {
        name: "p_canonical_content",
        kind: "client",
        key: "canonical_content",
        type: "jsonb",
        required: true,
      },
      { name: "p_canonical_text", kind: "canon", of: "p_canonical_content" },
      { name: "p_content_hash", kind: "hash", of: "p_canonical_content" },
      {
        name: "p_effective_at",
        kind: "client",
        key: "effective_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_supersedes_policy_artifact_id",
        kind: "client",
        key: "supersedes_policy_artifact_id",
        type: "uuid",
        required: false,
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_audience_scope: {
    fn: "spatial.append_audience_scope",
    arity: 8,
    primary: "p_content_hash",
    params: [
      {
        name: "p_audience_code",
        kind: "client",
        key: "audience_code",
        type: "text",
        required: true,
      },
      {
        name: "p_audience_version",
        kind: "client",
        key: "audience_version",
        type: "text",
        required: true,
      },
      {
        name: "p_canonical_capabilities",
        kind: "client",
        key: "canonical_capabilities",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_canonical_text",
        kind: "canon",
        of: "p_canonical_capabilities",
      },
      { name: "p_content_hash", kind: "hash", of: "p_canonical_capabilities" },
      {
        name: "p_effective_at",
        kind: "client",
        key: "effective_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_supersedes_audience_scope_id",
        kind: "client",
        key: "supersedes_audience_scope_id",
        type: "uuid",
        required: false,
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_assertion: {
    fn: "spatial.append_assertion",
    arity: 7,
    primary: "p_assertion_fingerprint",
    params: [
      {
        name: "p_graph_node_id",
        kind: "client",
        key: "graph_node_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_relationship_scope_key",
        kind: "client",
        key: "relationship_scope_key",
        type: "text",
        required: true,
      },
      {
        name: "p_scope_policy_artifact_id",
        kind: "client",
        key: "scope_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_identity_payload",
        kind: "client",
        key: "identity_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_identity_canonical_text",
        kind: "canon",
        of: "p_identity_payload",
      },
      {
        name: "p_assertion_fingerprint",
        kind: "hash",
        of: "p_identity_payload",
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_assertion_revision: {
    fn: "spatial.append_assertion_revision",
    arity: 23,
    primary: "p_revision_fingerprint",
    params: [
      {
        name: "p_assertion_id",
        kind: "client",
        key: "assertion_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_location_role",
        kind: "client",
        key: "location_role",
        type: "text",
        required: true,
      },
      {
        name: "p_relationship_qualifier",
        kind: "client",
        key: "relationship_qualifier",
        type: "text",
        required: true,
      },
      {
        name: "p_canonical_place_id",
        kind: "client",
        key: "canonical_place_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_evidence_precision",
        kind: "client",
        key: "evidence_precision",
        type: "text",
        required: true,
      },
      {
        name: "p_internal_geometry_snapshot_id",
        kind: "client",
        key: "internal_geometry_snapshot_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_valid_time_precision",
        kind: "client",
        key: "valid_time_precision",
        type: "text",
        required: true,
      },
      {
        name: "p_source_native_time",
        kind: "client",
        key: "source_native_time",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_guard_start_utc",
        kind: "client",
        key: "guard_start_utc",
        type: "timestamptz",
        required: false,
      },
      {
        name: "p_guard_end_utc",
        kind: "client",
        key: "guard_end_utc",
        type: "timestamptz",
        required: false,
      },
      {
        name: "p_temporal_policy_artifact_id",
        kind: "client",
        key: "temporal_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_uncertainty_class",
        kind: "client",
        key: "uncertainty_class",
        type: "text",
        required: false,
      },
      {
        name: "p_uncertainty_note",
        kind: "client",
        key: "uncertainty_note",
        type: "text",
        required: false,
      },
      {
        name: "p_revision_payload",
        kind: "client",
        key: "revision_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_revision_canonical_text",
        kind: "canon",
        of: "p_revision_payload",
      },
      {
        name: "p_revision_fingerprint",
        kind: "hash",
        of: "p_revision_payload",
      },
      {
        name: "p_node_payload",
        kind: "client",
        key: "node_payload",
        type: "jsonb",
        required: true,
      },
      { name: "p_node_canonical_text", kind: "canon", of: "p_node_payload" },
      { name: "p_node_snapshot_hash", kind: "hash", of: "p_node_payload" },
      {
        name: "p_place_payload",
        kind: "client",
        key: "place_payload",
        type: "jsonb",
        required: true,
      },
      { name: "p_place_canonical_text", kind: "canon", of: "p_place_payload" },
      { name: "p_place_snapshot_hash", kind: "hash", of: "p_place_payload" },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_revision_lineage: {
    fn: "spatial.append_revision_lineage",
    arity: 7,
    primary: "p_lineage_fingerprint",
    params: [
      {
        name: "p_from_revision_id",
        kind: "client",
        key: "from_revision_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_to_revision_id",
        kind: "client",
        key: "to_revision_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_relationship_type",
        kind: "client",
        key: "relationship_type",
        type: "text",
        required: true,
      },
      {
        name: "p_lineage_payload",
        kind: "client",
        key: "lineage_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_lineage_canonical_text",
        kind: "canon",
        of: "p_lineage_payload",
      },
      { name: "p_lineage_fingerprint", kind: "hash", of: "p_lineage_payload" },
      { name: "p_run_id", kind: "run" },
    ],
  },
  register_evidence_artifact: {
    fn: "spatial.register_evidence_artifact",
    arity: 14,
    primary: "p_registry_fingerprint",
    params: [
      {
        name: "p_artifact_type_code",
        kind: "client",
        key: "artifact_type_code",
        type: "text",
        required: true,
      },
      {
        name: "p_native_id",
        kind: "client",
        key: "native_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_stable_artifact_key",
        kind: "client",
        key: "stable_artifact_key",
        type: "text",
        required: true,
      },
      {
        name: "p_validation_policy_artifact_id",
        kind: "client",
        key: "validation_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_registry_payload",
        kind: "client",
        key: "registry_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_registry_canonical_text",
        kind: "canon",
        of: "p_registry_payload",
      },
      {
        name: "p_registry_fingerprint",
        kind: "hash",
        of: "p_registry_payload",
      },
      {
        name: "p_source_node_payload",
        kind: "client",
        key: "source_node_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_source_node_canonical_text",
        kind: "canon",
        of: "p_source_node_payload",
      },
      {
        name: "p_source_node_snapshot_hash",
        kind: "hash",
        of: "p_source_node_payload",
      },
      {
        name: "p_source_graph_payload",
        kind: "client",
        key: "source_graph_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_source_graph_canonical_text",
        kind: "canon",
        of: "p_source_graph_payload",
      },
      {
        name: "p_source_graph_association_fingerprint",
        kind: "hash",
        of: "p_source_graph_payload",
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_evidence_snapshot: {
    fn: "spatial.append_evidence_snapshot",
    arity: 20,
    primary: "p_snapshot_fingerprint",
    params: [
      {
        name: "p_registry_id",
        kind: "client",
        key: "registry_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_source_field",
        kind: "client",
        key: "source_field",
        type: "text",
        required: true,
      },
      {
        name: "p_span_start",
        kind: "client",
        key: "span_start",
        type: "integer",
        required: false,
      },
      {
        name: "p_span_end",
        kind: "client",
        key: "span_end",
        type: "integer",
        required: false,
      },
      {
        name: "p_span_coordinate_system",
        kind: "client",
        key: "span_coordinate_system",
        type: "text",
        required: true,
      },
      {
        name: "p_normalization_version",
        kind: "client",
        key: "normalization_version",
        type: "text",
        required: true,
      },
      {
        name: "p_encoding_version",
        kind: "client",
        key: "encoding_version",
        type: "text",
        required: true,
      },
      {
        name: "p_content_hash",
        kind: "client",
        key: "content_hash",
        type: "sha256hex",
        required: true,
      },
      {
        name: "p_source_version_identifier",
        kind: "client",
        key: "source_version_identifier",
        type: "text",
        required: false,
      },
      {
        name: "p_source_acquired_at",
        kind: "client",
        key: "source_acquired_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_capture_mode",
        kind: "client",
        key: "capture_mode",
        type: "text",
        required: true,
      },
      {
        name: "p_capture_policy_artifact_id",
        kind: "client",
        key: "capture_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_retention_policy_artifact_id",
        kind: "client",
        key: "retention_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_retention_classification",
        kind: "client",
        key: "retention_classification",
        type: "text",
        required: true,
      },
      {
        name: "p_access_scope",
        kind: "client",
        key: "access_scope",
        type: "text",
        required: true,
      },
      {
        name: "p_immutable_capture_ref",
        kind: "client",
        key: "immutable_capture_ref",
        type: "text",
        required: false,
      },
      {
        name: "p_snapshot_payload",
        kind: "client",
        key: "snapshot_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_snapshot_canonical_text",
        kind: "canon",
        of: "p_snapshot_payload",
      },
      {
        name: "p_snapshot_fingerprint",
        kind: "hash",
        of: "p_snapshot_payload",
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_revision_evidence: {
    fn: "spatial.append_revision_evidence",
    arity: 7,
    primary: "p_linkage_fingerprint",
    params: [
      {
        name: "p_revision_id",
        kind: "client",
        key: "revision_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_evidence_snapshot_id",
        kind: "client",
        key: "evidence_snapshot_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_evidence_role",
        kind: "client",
        key: "evidence_role",
        type: "text",
        required: true,
      },
      {
        name: "p_linkage_payload",
        kind: "client",
        key: "linkage_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_linkage_canonical_text",
        kind: "canon",
        of: "p_linkage_payload",
      },
      { name: "p_linkage_fingerprint", kind: "hash", of: "p_linkage_payload" },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_geometry_snapshot: {
    fn: "spatial.append_geometry_snapshot",
    arity: 15,
    primary: "p_geometry_hash",
    params: [
      {
        name: "p_representation_kind",
        kind: "client",
        key: "representation_kind",
        type: "text",
        required: true,
      },
      {
        name: "p_canonical_geojson",
        kind: "client",
        key: "canonical_geojson",
        type: "jsonb",
        required: false,
      },
      {
        name: "p_canonical_place_id",
        kind: "client",
        key: "canonical_place_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_place_payload",
        kind: "client",
        key: "place_payload",
        type: "jsonb",
        required: true,
      },
      { name: "p_place_canonical_text", kind: "canon", of: "p_place_payload" },
      { name: "p_place_snapshot_hash", kind: "hash", of: "p_place_payload" },
      {
        name: "p_geometry_precision",
        kind: "client",
        key: "geometry_precision",
        type: "text",
        required: true,
      },
      {
        name: "p_geometry_source_kind",
        kind: "client",
        key: "geometry_source_kind",
        type: "text",
        required: true,
      },
      {
        name: "p_geometry_source_version",
        kind: "client",
        key: "geometry_source_version",
        type: "text",
        required: false,
      },
      {
        name: "p_compatibility_policy_artifact_id",
        kind: "client",
        key: "compatibility_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_geometry_payload",
        kind: "client",
        key: "geometry_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_geometry_canonical_text",
        kind: "canon",
        of: "p_geometry_payload",
      },
      { name: "p_geometry_hash", kind: "hash", of: "p_geometry_payload" },
      {
        name: "p_capture_basis",
        kind: "client",
        key: "capture_basis",
        type: "text",
        required: true,
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_evidence_condition_event: {
    fn: "spatial.append_evidence_condition_event",
    arity: 10,
    primary: "p_event_fingerprint",
    params: [
      {
        name: "p_evidence_snapshot_id",
        kind: "client",
        key: "evidence_snapshot_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_condition",
        kind: "client",
        key: "condition",
        type: "text",
        required: true,
      },
      {
        name: "p_source_change_event_id",
        kind: "client",
        key: "source_change_event_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_condition_policy_artifact_id",
        kind: "client",
        key: "condition_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_reason_code",
        kind: "client",
        key: "reason_code",
        type: "text",
        required: true,
      },
      {
        name: "p_observed_at",
        kind: "client",
        key: "observed_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_event_payload",
        kind: "client",
        key: "event_payload",
        type: "jsonb",
        required: true,
      },
      { name: "p_event_canonical_text", kind: "canon", of: "p_event_payload" },
      { name: "p_event_fingerprint", kind: "hash", of: "p_event_payload" },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_review_decision: {
    fn: "spatial.append_review_decision",
    arity: 11,
    primary: "p_decision_fingerprint",
    params: [
      {
        name: "p_revision_id",
        kind: "client",
        key: "revision_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_support_disposition",
        kind: "client",
        key: "support_disposition",
        type: "text",
        required: true,
      },
      {
        name: "p_review_mode",
        kind: "client",
        key: "review_mode",
        type: "text",
        required: true,
      },
      {
        name: "p_review_outcome_basis",
        kind: "client",
        key: "review_outcome_basis",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_review_policy_artifact_id",
        kind: "client",
        key: "review_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_effective_at",
        kind: "client",
        key: "effective_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_reason_code",
        kind: "client",
        key: "reason_code",
        type: "text",
        required: true,
      },
      {
        name: "p_decision_payload",
        kind: "client",
        key: "decision_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_decision_canonical_text",
        kind: "canon",
        of: "p_decision_payload",
      },
      {
        name: "p_decision_fingerprint",
        kind: "hash",
        of: "p_decision_payload",
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
  append_release_decision: {
    fn: "spatial.append_release_decision",
    arity: 12,
    primary: "p_decision_fingerprint",
    params: [
      {
        name: "p_revision_id",
        kind: "client",
        key: "revision_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_audience_scope_id",
        kind: "client",
        key: "audience_scope_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_release_policy_artifact_id",
        kind: "client",
        key: "release_policy_artifact_id",
        type: "uuid",
        required: true,
      },
      {
        name: "p_decision_disposition",
        kind: "client",
        key: "decision_disposition",
        type: "text",
        required: true,
      },
      {
        name: "p_predecessor_release_decision_id",
        kind: "client",
        key: "predecessor_release_decision_id",
        type: "uuid",
        required: false,
      },
      {
        name: "p_decided_at",
        kind: "client",
        key: "decided_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_effective_at",
        kind: "client",
        key: "effective_at",
        type: "timestamptz",
        required: true,
      },
      {
        name: "p_reason_code",
        kind: "client",
        key: "reason_code",
        type: "text",
        required: true,
      },
      {
        name: "p_decision_payload",
        kind: "client",
        key: "decision_payload",
        type: "jsonb",
        required: true,
      },
      {
        name: "p_decision_canonical_text",
        kind: "canon",
        of: "p_decision_payload",
      },
      {
        name: "p_decision_fingerprint",
        kind: "hash",
        of: "p_decision_payload",
      },
      { name: "p_run_id", kind: "run" },
    ],
  },
} as const satisfies Record<string, OperationSpec>;

export type OperationName = keyof typeof OPERATIONS;

// Loose view for generic/introspection code (tests, validators).
export const OPERATION_LIST: Record<string, OperationSpec> = OPERATIONS;
