import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
import {execFileSync} from 'node:child_process'
// Actual local App with only its backend composition module replaced by explicit
// synthetic contract rows. No live reader, source rights, hardware, performance
// or release claim. All nonlocal browser requests are aborted.
import {PROJECTION_FIXTURE_COLUMNS,makeClusteringContractRows} from './worldViewProjectionFixture.mjs'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'/opt/codex/cua_node/lib/node_modules/playwright/index.mjs')
const origin=process.env.MIP_A11Y_ORIGIN??'http://127.0.0.1:4183',base=origin+'/media-intelligence-platform-v2/',out=process.env.MIP_A11Y_RECEIPTS??'/workspace/mip-lane-a11y-receipts/whole-journey'
await mkdir(out,{recursive:true})
const template={...Object.fromEntries(PROJECTION_FIXTURE_COLUMNS.map(k=>[k,null])),projection_contract_version:'v1',mip_object_id:'synthetic',subject_graph_node_id:'synthetic',revision_id:'synthetic',revision_ordinal:1,revision_known_at_utc:'2025-12-01T00:00:00Z',review_effective_at_utc:'2026-01-01T12:00:00Z',release_effective_at_utc:'2025-12-01T00:00:00Z',precision_class:'city',object_type:'event',spatial_role:'event',geometry_status:'coarsened_to_precision_class',release_state:'released',review_state:'reviewed',valid_from_utc:'2026-01-01T00:00:00Z',valid_to_utc:'2026-01-02T00:00:00Z',display_geometry:{type:'Point',coordinates:[-81.7,41.4]},evidence_refs:[]}
const rows=makeClusteringContractRows(template,'US-local',{count:3,dense:false}),nodes=rows.map((r,i)=>({id:r.subject_graph_node_id,label:`Controlled event ${i+1}`,type:'event',occurred_at:r.valid_from_utc,metadata:{synthetic_fixture:true}})),edges=[{id:'controlled-edge',source:nodes[0].id,target:nodes[1].id,type:'association',label:'Synthetic documented association',metadata:{synthetic_fixture:true}}]
const backendModule=`import {createPublicDataBackend} from './publicDataBackend.js';import {createInvestigationBackend} from './investigationBackend.js';const original=createPublicDataBackend(null),rows=${JSON.stringify(rows)},nodes=${JSON.stringify(nodes)},edges=${JSON.stringify(edges)};export const mipBackend={investigations:createInvestigationBackend(null),publicData:{...original,loadGraph:async()=>({source:'isolated-synthetic-fixture',nodes,edges}),spatial:{...original.spatial,loadSpatialProjection:async()=>({status:'ok',reason:null,rows,error:null,loadedAt:'2026-10-02T00:00:00Z'}),loadWorldViewGraph:async()=>({status:'ok',nodes,edges,edgesUnavailable:null,error:null})}}};`
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']})
const report={candidate:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),browser:browser.version(),origin,qualification:'Controlled local synthetic backend module; no provider/backend requests or real-source qualification.',checks:[],failures:[],blocked:[],blockedRequestCount:0,fixtureModuleReads:0,crossViewEnabled:process.env.MIP_A11Y_CROSS_VIEW!=='0'}
try{for(const viewport of [{width:1280,height:900},{width:390,height:844},{width:640,height:360}]){
 const page=await browser.newPage({viewport,hasTouch:viewport.width<=767}),errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin===origin){if(u.pathname.endsWith('/src/lib/mipBackend.js')){report.fixtureModuleReads++;return route.fulfill({status:200,contentType:'application/javascript',body:backendModule})};return route.continue()}if(['data:','blob:'].includes(u.protocol))return route.continue();report.blockedRequestCount++;if(report.blocked.length<20)report.blocked.push(u.origin+u.pathname);return route.abort()})
 await page.goto(base+'?worldViewPrototype=1#/event/'+nodes[0].id+'/world');await page.locator('.wv-view').waitFor();await page.getByRole('region',{name:'Active World View sources',exact:true}).waitFor()
 await page.waitForFunction(()=>document.querySelector('.wv-inspector')?.textContent.includes('Synthetic clustering fixture row 1'),{},{timeout:30000})
 const canonical=()=>page.locator('[data-investigation-context]').first().evaluate(n=>({subject:n.dataset.canonicalSubjectId,asOf:n.dataset.asOfTime,range:n.dataset.selectedTimeRange}))
 const initial=await canonical(),modes=page.getByRole('tablist',{name:'World View mode',exact:true})
 const modeChecks=[]
 for(const name of ['Graph','Split','Map']){await modes.getByRole('tab',{name,exact:true}).focus();await page.keyboard.press('Enter');await page.waitForTimeout(200);assert.deepEqual(await canonical(),initial);const geometry=await page.locator('.wv-stage').evaluate(n=>({width:n.clientWidth,height:n.clientHeight,scrollWidth:n.scrollWidth}));await page.screenshot({path:`${out}/${viewport.width}x${viewport.height}-${name}.png`,fullPage:true});modeChecks.push({name,geometry})}
 await modes.getByRole('tab',{name:'Map',exact:true}).focus();await page.keyboard.press('ArrowRight');const modeAfterArrow=await page.locator('.wv-view').getAttribute('data-wv-mode'),focusAfterArrow=await page.locator(':focus').textContent();assert.equal(modeAfterArrow,'graph');assert.equal(focusAfterArrow,'Graph');await modes.getByRole('tab',{name:'Map',exact:true}).focus();await page.keyboard.press('Enter')
 await page.locator('.wv-view').evaluate(()=>window.__MIP_WORLD_VIEW_CAMERA_PROBE__?.setCameraState(JSON.stringify({version:1,lon:-81.7,lat:41.4,heightMeters:100000,headingDegrees:0,pitchDegrees:-90,rollDegrees:0})))
 await page.waitForTimeout(500);const flight=page.getByRole('button',{name:'Stop camera flight',exact:true});if(await flight.count())await flight.click()
 const open=page.getByRole('button',{name:'Open selected spatial context',exact:true});let inspectorFocus='control unavailable'
 if(await open.count()){await open.click();const inspect=page.getByRole('button',{name:'Open inspector',exact:true});if(await inspect.count()){await inspect.focus();await page.keyboard.press('Enter');inspectorFocus=await page.locator(':focus').evaluate(n=>({tag:n.tagName,label:n.getAttribute('aria-label'),class:n.className}))}}
 assert.equal(inspectorFocus.label,'Selected-event inspector');const selectedModules=page.getByRole('tablist',{name:'Selected record modules',exact:true});if(await selectedModules.count()){await selectedModules.getByRole('tab',{name:'Context',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal((await page.locator(':focus').textContent()).trim(),'Sources')}
 const receipt={viewport,initial,modeChecks,modeAfterArrow,focusAfterArrow,inspectorFocus,errors};report.checks.push(receipt);
 if(report.crossViewEnabled){const nav=page.getByRole('navigation',{name:'Evidence views',exact:true});await nav.getByRole('button',{name:'Graph',exact:true}).focus();await page.keyboard.press('Enter');if(viewport.width<=767){const hub=page.locator('.hub-item').filter({hasText:'Controlled event 1'});await hub.focus();await page.keyboard.press('Enter');const graphSearch=page.locator('.graph-search input');await graphSearch.fill('Controlled event 1');await page.locator('.graph-search-results button').filter({hasText:'Controlled event 1'}).focus();await page.keyboard.press('Enter')}await page.locator('.article-panel').waitFor();assert.deepEqual(await canonical(),initial);await nav.getByRole('button',{name:'World View',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('.wv-view').waitFor();assert.deepEqual(await canonical(),initial);receipt.graphWorldContextPreserved=true}
 const enterExplore=page.getByRole('button',{name:'Explore World View',exact:true});await enterExplore.focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Close Explore World View',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Close Explore World View',exact:true}).waitFor({state:'hidden'});assert.equal(await enterExplore.evaluate(n=>n===document.activeElement),true);assert.deepEqual(await canonical(),initial);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);assert.deepEqual(errors,[])
 receipt.worldExploreKeyboardRestore=true;receipt.overflow=overflow;await page.close()
} }catch(e){report.failures.push(e.stack??String(e));process.exitCode=1}finally{await browser.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,blocked:report.blocked.slice(0,3)},null,2))}
