// SYNTHETIC ONLY. Own disposable network-none PG17.6; never accepts DB URL/credentials.
import {readFile,writeFile,mkdir,mkdtemp} from 'node:fs/promises';import {spawnSync,spawn} from 'node:child_process';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url)),fixture=path.join(root,'scripts/qualification/qik-audit-route-synthetic');
const hash=s=>createHash('sha256').update(s).digest('hex'),quote=s=>"'"+s.replaceAll("'","''")+"'";
export async function runQikAuditRouteSyntheticQualification({outputDir}={}){
 const out=outputDir||await mkdtemp('/tmp/qik-synthetic-qualification-');await mkdir(out,{recursive:true});
 const historical=await readFile(path.join(fixture,'historical-948f83d.sql'),'utf8'),proposal=await readFile(path.join(root,'scripts/qualification/qik-audit-route-transform-proposal-20261002.sql'),'utf8'),bootstrap=await readFile(path.join(fixture,'bootstrap.sql'),'utf8'),extras=await readFile(path.join(fixture,'extras.sql'),'utf8');
 assert.equal(hash(historical),'4e574834ecae813985733c8c39041c914ac414682524afad4d320e4af74ddffa');assert.equal(hash(proposal),'5be14204dbd68b44ccaba07222bd6a5b4f9d9f627ce4750fce596211e6d6fb46');
 const name=`qik-synthetic-${process.pid}`,results=[],executed=[];let created=false;
 const docker=(args,input)=>{const r=spawnSync('docker',args,{input,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout};
 const pg=(sql,user='postgres')=>docker(['exec','-i',name,'psql','-U',user,'-d','postgres','-X','-v','ON_ERROR_STOP=1','-At'],sql);
 const baseline=`SELECT jsonb_build_object('row',(SELECT jsonb_agg(to_jsonb(t) ORDER BY id) FROM mip_factual.audit_connection t),'relacl',(SELECT relacl::text FROM pg_class WHERE oid='mip_factual.audit_connection'::regclass),'attacl',(SELECT jsonb_agg(jsonb_build_array(attname,attacl::text) ORDER BY attnum) FROM pg_attribute WHERE attrelid='mip_factual.audit_connection'::regclass AND attnum>0),'membership',(SELECT jsonb_agg(jsonb_build_array(roleid::regrole::text,grantor::regrole::text,admin_option,inherit_option,set_option) ORDER BY roleid::regrole::text,grantor::regrole::text) FROM pg_auth_members WHERE member='postgres'::regrole),'roles',(SELECT jsonb_agg(jsonb_build_array(rolname,rolsuper,rolbypassrls) ORDER BY rolname) FROM pg_roles WHERE rolname IN ('postgres','mip_cutover_schema_owner_v1')),'rls',(SELECT jsonb_build_array(relowner::regrole::text,relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid='mip_factual.audit_connection'::regclass),'policies',(SELECT jsonb_agg(to_jsonb(p) ORDER BY polname) FROM pg_policy p WHERE polrelid='mip_factual.audit_connection'::regclass)) AS value`;
 const restoreAssert=`DO $restore$ BEGIN IF (SELECT value-'row' FROM qik_baseline) IS DISTINCT FROM (${baseline})-'row' THEN RAISE EXCEPTION 'synthetic_authority_restoration_failed'; END IF; END $restore$;`;
 const cases=[
 {name:'preexisting-column-privilege-success',extraPrivilege:true,password:'dummy_prior_acl',success:true},
 {name:'ordinary-success',password:'dummy:ordinary%2Fsentinel',success:true},
 {name:'query-sentinel-success',password:'dummy_sslrootcert=system_sentinel',success:true},
 {name:'username-sentinel-success',password:'dummy_postgresql://mip_native_audit_v1.qikvmopbtijoebdqosyq:_sentinel',success:true},
 {name:'historical-query-sentinel-red',password:'dummy_sslrootcert=system_sentinel',historical:true,error:'probe_refused'},
 {name:'historical-username-sentinel-red',password:'dummy_postgresql://mip_native_audit_v1.qikvmopbtijoebdqosyq:_sentinel',historical:true,error:'probe_refused'},
 {name:'missing-update',password:'dummy',grant:false,error:'grant_missing'},
 {name:'missing-operation',mutation:'DELETE FROM mip_comparison_install.receipts;',error:'state_refused'},
 {name:'wrong-operation',mutation:"UPDATE mip_comparison_install.receipts SET operation_id='wrong';",error:'state_refused'},
 {name:'duplicate-singleton',mutation:'INSERT INTO mip_native_activation.head VALUES(true,null);',error:'state_refused'},
 {name:'malformed-source',mutation:"UPDATE mip_factual.audit_connection SET connection_string='synthetic_invalid';",error:'source_refused'},
 {name:'duplicate-parameter',mutation:"UPDATE mip_factual.audit_connection SET connection_string=connection_string||'&sslmode=verify-full';",error:'source_refused'},
 {name:'already-applied',mutation:"UPDATE mip_factual.audit_connection SET connection_string='postgresql://mip_native_audit_v1:dummy@db.qikvmopbtijoebdqosyq.supabase.co:5432/postgres?sslrootcert=%2Fsynthetic%2Fca.pem&sslmode=verify-full&connect_timeout=5';",error:'already_applied'},
 {name:'bad-auditor',mutation:"PERFORM set_config('synthetic.probe_mode','badidentity',true);",error:'probe_refused'},
 {name:'bad-tls',mutation:"PERFORM set_config('synthetic.probe_mode','badtls',true);",error:'probe_refused'},
 {name:'rowcount-zero',mutation:"PERFORM set_config('synthetic.suppress_update','on',true);",error:'write_refused'},
 {name:'independent-session-lock-contention',error:'inflight',lock:true},
 ];
 try{
 docker(['run','--pull','never','-d','--name',name,'--network','none','-e','POSTGRES_USER=bootstrap_super','-e','POSTGRES_HOST_AUTH_METHOD=trust','postgres:17.6','-c','ssl_ca_file=/synthetic/ca.pem','-c','log_parameter_max_length_on_error=0']);created=true;
 for(let i=0;i<60;i++){const r=spawnSync('docker',['exec',name,'pg_isready','-h','127.0.0.1','-U','bootstrap_super'],{encoding:'utf8'});if(r.status===0)break;await new Promise(r=>setTimeout(r,100));if(i===59)throw Error('Synthetic postgres startup timeout')}
 pg(bootstrap+extras,'bootstrap_super');await writeFile(path.join(out,'executed-bootstrap.sql'),bootstrap+extras);
 const baselineBefore=JSON.parse(pg(baseline));assert.deepEqual(baselineBefore.membership,[['mip_cutover_schema_owner_v1','supabase_admin',true,false,false],['synthetic_reader','bootstrap_super',false,true,false]]);assert.deepEqual(baselineBefore.roles,[['mip_cutover_schema_owner_v1',false,false],['postgres',false,true]]);assert.deepEqual(baselineBefore.rls,['mip_cutover_schema_owner_v1',true,true]);
 for(const c of cases){
 if(c.extraPrivilege)pg('GRANT REFERENCES(id) ON mip_factual.audit_connection TO postgres;','bootstrap_super');
 const caseBaseline=JSON.parse(pg(baseline));
 let holder;const password=c.password||'dummy';const uri='postgresql://mip_native_audit_v1.qikvmopbtijoebdqosyq:'+password+'@aws-0-us-west-1.pooler.supabase.com:5432/postgres?sslrootcert=system&sslmode=verify-full&connect_timeout=5';
 const body=c.historical?historical:proposal;
 const invoke=c.error?`BEGIN ${c.mutation||''} EXECUTE $source$${body}$source$; RAISE EXCEPTION 'synthetic_expected_refusal_missing'; EXCEPTION WHEN others THEN IF SQLERRM <> ${quote('qik_audit_route_'+c.error)} THEN RAISE; END IF; END;`:`EXECUTE $source$${body}$source$;`;
 const sql=`BEGIN;CREATE TEMP TABLE qik_baseline ON COMMIT DROP AS ${baseline};\nGRANT mip_cutover_schema_owner_v1 TO postgres WITH ADMIN FALSE, INHERIT FALSE, SET TRUE;\nSET ROLE mip_cutover_schema_owner_v1;DO $owner$ DECLARE n integer;BEGIN UPDATE mip_factual.audit_connection SET connection_string=connection_string WHERE id;GET DIAGNOSTICS n=ROW_COUNT;IF n<>0 THEN RAISE EXCEPTION 'synthetic_owner_force_rls_not_zero';END IF;END $owner$;${c.grant===false?'':'GRANT UPDATE(connection_string) ON mip_factual.audit_connection TO postgres;'}RESET ROLE;\n${c.grant===false?'':`UPDATE mip_factual.audit_connection SET connection_string=${quote(uri)} WHERE id;`}SELECT set_config('synthetic.expected_password',${quote(password)},true);\nDO $outer$ BEGIN ${invoke} END $outer$;\n${c.error?`DO $unchanged$ BEGIN IF (SELECT connection_string FROM mip_factual.audit_connection WHERE id) IS DISTINCT FROM ${c.grant===false?"(SELECT value->'row'->0->>'connection_string' FROM qik_baseline)":quote(uri)} THEN RAISE EXCEPTION 'synthetic_refusal_changed_source_row'; END IF; END $unchanged$;`:''}
${c.success?`DO $post$ BEGIN IF NOT EXISTS(SELECT 1 FROM mip_factual.audit_connection WHERE id AND split_part(split_part(connection_string,'@',1),'mip_native_audit_v1:',2)=${quote(password)} AND position('@db.qikvmopbtijoebdqosyq.supabase.co:5432/postgres?' IN connection_string)>0) THEN RAISE EXCEPTION 'synthetic_target_or_password_failed'; END IF;END $post$;`:''}\nSET ROLE mip_cutover_schema_owner_v1;${c.grant===false?'':'REVOKE UPDATE(connection_string) ON mip_factual.audit_connection FROM postgres;'}RESET ROLE;\nREVOKE mip_cutover_schema_owner_v1 FROM postgres GRANTED BY postgres;\n${restoreAssert}\nDO $denial$ BEGIN IF has_column_privilege('postgres','mip_factual.audit_connection','connection_string','UPDATE') THEN RAISE EXCEPTION 'synthetic_update_cleanup_failed'; END IF; IF (SELECT count(*) FROM pg_auth_members WHERE member='postgres'::regrole AND roleid='mip_cutover_schema_owner_v1'::regrole AND grantor='postgres'::regrole)<>0 THEN RAISE EXCEPTION 'synthetic_stray_grantor_row'; END IF;END $denial$;SELECT 'WITHIN_TRANSACTION_SEMANTIC_AUTHORITY_RESTORED';SELECT 'PRE_ROLLBACK_ATTACL_EXACT:'||((SELECT value->'attacl' FROM qik_baseline)=(${baseline})->'attacl')::text;ROLLBACK;${baseline};`;
 await writeFile(path.join(out,`${c.name}-executed.sql`),sql);executed.push({case:c.name,sqlSha256:hash(sql),importedSourceSha256:hash(body)});
 try{
 if(c.lock){holder=spawn('docker',['exec','-i',name,'psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1','-At'],{stdio:['pipe','pipe','pipe']});let buffer='';await new Promise((resolve,reject)=>{holder.stdout.on('data',b=>{buffer+=b;if(buffer.includes('LOCK_READY'))resolve()});holder.on('error',reject);holder.stdin.end("BEGIN;SELECT pg_advisory_xact_lock(hashtextextended('qik-comparison-audit-v1',0));SELECT 'LOCK_READY';SELECT pg_sleep(3);ROLLBACK;")})}
 const stdout=pg(sql);assert.match(stdout,/WITHIN_TRANSACTION_SEMANTIC_AUTHORITY_RESTORED/);const after=JSON.parse(stdout.trim().split('\n').at(-1));assert.deepEqual(after,caseBaseline);assert.ok(stdout.includes('PRE_ROLLBACK_ATTACL_EXACT:true')); await writeFile(path.join(out,`${c.name}-receipt.txt`),stdout);results.push({name:c.name,pass:true,expectedRefusal:c.error||null,exactWithinTransactionAclMembershipGrantorRolesPoliciesRestored:true,semanticWithinTransactionAuthorityRestored:true,exactPreRollbackAttacl:stdout.includes('PRE_ROLLBACK_ATTACL_EXACT:true'),exactAfterRollbackRowAclMembershipGrantorRolesPoliciesRestored:true});
 }finally{if(holder)await new Promise(resolve=>holder.exitCode!==null?resolve():holder.once('close',resolve));if(c.extraPrivilege){pg('REVOKE REFERENCES(id) ON mip_factual.audit_connection FROM postgres;','bootstrap_super');assert.deepEqual(JSON.parse(pg(baseline)),baselineBefore)}}
 }
 const version=pg('SELECT version();');const manifest={runnerSha256:hash(await readFile(fileURLToPath(import.meta.url))),scope:'SYNTHETIC ONLY; no real CA/TLS/dblink/provider log qualification',head:spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).stdout.trim(),version,imageId:JSON.parse(docker(['inspect',name]))[0].Image,imageRepoDigests:JSON.parse(docker(['image','inspect','postgres:17.6']))[0].RepoDigests,networkMode:JSON.parse(docker(['inspect',name]))[0].HostConfig.NetworkMode,bootstrapSha256:hash(bootstrap),extrasSha256:hash(extras),historicalSha256:hash(historical),proposalSha256:hash(proposal),executed,results,pass:results.length,fail:0,baselineBefore,cleanup:'owned container removed in finally'};await writeFile(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return {outputDir:out,pass:results.length};
 }finally{if(created){docker(['rm','-f',name]);const remaining=docker(['ps','-a','--filter',`name=^/${name}$`,'--format','{{.ID}}']).trim();assert.equal(remaining,'','Owned container removal verified');try{const manifestPath=path.join(out,'manifest.json');const saved=JSON.parse(await readFile(manifestPath,'utf8'));saved.cleanup={ownedContainer:name,removed:true,remainingMatchingContainers:0};await writeFile(manifestPath,JSON.stringify(saved,null,2)+'\n')}catch(e){if(e.code!=='ENOENT')throw e}}}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){console.log(await runQikAuditRouteSyntheticQualification({outputDir:process.env.SYNTHETIC_OUTPUT_DIR}))}
