import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {readFile} from 'node:fs/promises'
const require=createRequire(import.meta.url)
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild')
const {chromium,webkit}=createRequire(process.env.MIP_BROWSER_PACKAGE+'/package.json')('playwright')
const bundle=await build({entryPoints:['verifier/hypothesis-browser/fixture.jsx'],bundle:true,write:false,
 format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'}})
// Actual application styles; remote font import omitted, system fallback only.
const css=(await Promise.all(['src/styles/tokens.css','src/index.css','src/styles/investigation-workspace-panels.css'].map(p=>readFile(p,'utf8')))).map(s=>s.split('\n').filter(line=>!line.startsWith('@import ')).join('\n')).join('\n')
for(const [engine,launcher] of Object.entries({chromium,webkit})){
 const browser=await launcher.launch({headless:true})
 try{
  const page=await browser.newPage(),requests=[],errors=[]
  await page.route('**/*',route=>{requests.push(route.request().url());return route.abort()})
  page.on('pageerror',e=>errors.push(e.message))
  for(const width of [1280,768,390,320]){
   await page.setViewportSize({width,height:1000})
   await page.setContent('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Synthetic hypothesis worker inspection</title><div id="root"></div>')
   await page.addStyleTag({content:css})
   await page.addScriptTag({content:bundle.outputFiles[0].text})
   const region=page.getByRole('region',{name:'Hypothesis worker attempts'})
   await region.waitFor()
   assert.equal(await page.evaluate(()=>window.synthetic.calls),0)
   const inspect=region.getByRole('button',{name:'Inspect worker attempts',exact:true})
   await inspect.focus();await page.keyboard.press('Enter')
   await region.getByText('Failed; retained for reconciliation',{exact:true}).waitFor()
   assert.equal(await page.evaluate(()=>window.synthetic.calls),1)
   assert.equal(await region.locator('li').count(),3)
   assert.ok((await region.innerText()).includes('Linked fresh generation'))
   assert.ok((await region.innerText()).includes('Fresh recovery of retained generation'))
   const recover=region.getByRole('button',{name:'Prepare fresh-generation recovery',exact:true})
   assert.equal(await recover.count(),1)
   assert.ok((await recover.boundingBox()).height>=44)
   await recover.focus();await page.keyboard.press('Enter')
   assert.deepEqual(await page.evaluate(()=>window.synthetic.recoveries),['00000000-0000-4000-8000-000000000023'])
   assert.equal(await page.evaluate(()=>window.synthetic.calls),1)
   assert.equal(await region.evaluate(el=>el.scrollWidth>el.clientWidth+1),false)
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)
   if(width===390)console.log('MIP_SYNTHETIC_WORKER_LEDGER_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await page.evaluate(()=>window.synthetic.mode='denied')
   await region.getByRole('button',{name:'Refresh worker attempts',exact:true}).click()
   await region.getByText('Worker attempts are unavailable under the current access context.',{exact:true}).waitFor()
   assert.equal(await region.locator('li').count(),0)
   assert.equal(await recover.count(),0)
   await page.evaluate(()=>window.renderSynthetic(null))
   await region.waitFor({state:'detached'})
   await page.evaluate(()=>window.renderSyntheticAssessment())
   const panel=page.locator('.piw-hypothesis-assessment')
   await panel.getByRole('heading',{name:'What explains the fictional contract award?',exact:true}).waitFor()
   await panel.getByText('Inferred assessment, not an established finding.',{exact:true}).waitFor()
   await panel.getByText('Review: unreviewed · Private; publication disabled.',{exact:true}).waitFor()
   assert.equal(await panel.getByRole('heading',{name:'Saved revision record',exact:true}).count(),0)
   const disclosure=panel.locator('summary')
   await disclosure.focus();await page.keyboard.press('Enter')
   await panel.getByRole('heading',{name:'Saved revision record',exact:true}).waitFor()
   assert.equal(await panel.getByRole('heading',{name:'Improper influence affected the award.',exact:true}).count(),1)
   assert.equal(await panel.getByRole('heading',{name:'A legitimate selection process determined the award.',exact:true}).count(),1)
   const visible=await panel.innerText()
   assert.ok(visible.includes('Source publication: 2026-09-12 (date only)'))
   assert.ok(visible.includes('2026-09-13 10:00:00.123456 UTC'))
   assert.ok(visible.includes('Shared origins are not independent corroboration.'))
   assert.ok(visible.includes('A dependency changed. Reassessment is pending'))
   for(const title of ['Likelihood','Confidence in this likelihood assessment','Diagnostic relevance','Evidence quality','Overall assessment confidence'])
    assert.ok(visible.includes(title))
   assert.ok(!visible.includes('50%'))
   assert.equal(await panel.evaluate(el=>el.scrollWidth>el.clientWidth+1),false)
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)
   const revision=panel.getByRole('heading',{name:'Saved revision record',exact:true})
   await revision.scrollIntoViewIfNeeded()
   const box=await revision.boundingBox()
   assert.ok(box.y>=0&&box.y+box.height<=1000)
   if(width===390)console.log('MIP_SYNTHETIC_SAVED_REVISION_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await panel.getByRole('heading',{name:'What explains the fictional contract award?',exact:true}).scrollIntoViewIfNeeded()
   if(width===390)console.log('MIP_SYNTHETIC_SAVED_ASSESSMENT_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await disclosure.focus();await page.keyboard.press('Enter')
   await panel.getByRole('heading',{name:'Saved revision record',exact:true}).waitFor({state:'detached'})

  }
  assert.deepEqual(requests,[]);assert.deepEqual(errors,[])
  console.log('MIP_SYNTHETIC_HYPOTHESIS_BROWSER_PASS='+JSON.stringify({engine,widths:[1280,768,390,320],
   keyboardInspection:true,reciprocalRecoveryLinks:true,onlyUnlinkedFailureRecoverable:true,
   noAutomaticRetry:true,deniedRecordsCleared:true,logoutCleared:true,networkRequests:0,
   savedRevisionReachableByScrolling:true,savedAssessmentDisclosure:true,separateMissingEstimates:true,sourceClocks:true,pendingReassessment:true,systemFontFallback:true,scope:'synthetic_generation_ledger_and_saved_assessment',productionQualified:false}))
 }finally{await browser.close()}
}
