import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {readFile} from 'node:fs/promises'
const require=createRequire(import.meta.url)
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild')
const {chromium,webkit}=createRequire(process.env.MIP_BROWSER_PACKAGE+'/package.json')('playwright')
const bundle=await build({entryPoints:['verifier/hypothesis-browser/fixture.jsx'],bundle:true,write:false,
 format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'}})
// Actual application styles; remote font import omitted, system fallback only.
const css=(await Promise.all(['src/styles/tokens.css','src/index.css','src/styles/investigation-workspace-panels.css'].map(p=>readFile(p,'utf8')))).map(s=>s.split('\n').filter(line=>!line.startsWith('@import ')).join('\n')).join('\n')
for(const [engine,launcher] of Object.entries({chromium,webkit})){
 const browser=await launcher.launch({headless:true})
 try{
  const page=await browser.newPage(),requests=[],errors=[]
  // Intercept a reserved synthetic origin to provide a secure WebCrypto context.
  // This document is fulfilled in-process; it never reaches DNS or a server.
  await page.route('**/*',route=>{
   if(route.request().url()==='https://mip-synthetic.invalid/'&&route.request().isNavigationRequest()&&route.request().frame()===page.mainFrame())
    return route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Synthetic hypothesis inspection</title><div id="root"></div>'})
   requests.push(route.request().url());return route.abort()
  })
  page.on('pageerror',e=>errors.push(e.message))
  for(const width of [1280,768,390,320]){
   await page.setViewportSize({width,height:1000})
   await page.goto('https://mip-synthetic.invalid/')
   await page.addStyleTag({content:css})
   await page.addScriptTag({content:bundle.outputFiles[0].text})
   const region=page.getByRole('region',{name:'Hypothesis worker attempts'})
   await region.waitFor()
   assert.equal(await page.evaluate(()=>window.synthetic.calls),0)
   const inspect=region.getByRole('button',{name:'Inspect worker attempts',exact:true})
   await inspect.focus();await page.keyboard.press('Enter')
   await region.getByText('Failed; retained for reconciliation',{exact:true}).waitFor()
   assert.equal(await page.evaluate(()=>window.synthetic.calls),1)
   assert.equal(await region.locator('li').count(),3)
   assert.ok((await region.innerText()).includes('Linked fresh generation'))
   assert.ok((await region.innerText()).includes('Fresh recovery of retained generation'))
   const recover=region.getByRole('button',{name:'Prepare fresh-generation recovery',exact:true})
   assert.equal(await recover.count(),1)
   assert.ok((await recover.boundingBox()).height>=44)
   await recover.focus();await page.keyboard.press('Enter')
   assert.deepEqual(await page.evaluate(()=>window.synthetic.recoveries),['00000000-0000-4000-8000-000000000023'])
   assert.equal(await page.evaluate(()=>window.synthetic.calls),1)
   assert.equal(await region.evaluate(el=>el.scrollWidth>el.clientWidth+1),false)
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)
   if(width===390)console.log('MIP_SYNTHETIC_WORKER_LEDGER_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await page.evaluate(()=>window.synthetic.mode='denied')
   await region.getByRole('button',{name:'Refresh worker attempts',exact:true}).click()
   await region.getByText('Worker attempts are unavailable under the current access context.',{exact:true}).waitFor()
   assert.equal(await region.locator('li').count(),0)
   assert.equal(await recover.count(),0)
   await page.evaluate(()=>window.renderSynthetic(null))
   await region.waitFor({state:'detached'})
   await page.evaluate(()=>window.renderSyntheticAssessment())
   const panel=page.locator('.piw-hypothesis-assessment')
   await panel.getByRole('heading',{name:'What explains the fictional contract award?',exact:true}).waitFor()
   await panel.getByText('Inferred assessment, not an established finding.',{exact:true}).waitFor()
   await panel.getByText('Review: unreviewed · Private; publication disabled.',{exact:true}).waitFor()
   assert.equal(await panel.getByRole('heading',{name:'Saved revision record',exact:true}).count(),0)
   const disclosure=panel.locator('summary')
   await disclosure.focus();await page.keyboard.press('Enter')
   await panel.getByRole('heading',{name:'Saved revision record',exact:true}).waitFor()
   assert.equal(await panel.getByRole('heading',{name:'Improper influence affected the award.',exact:true}).count(),1)
   assert.equal(await panel.getByRole('heading',{name:'A legitimate selection process determined the award.',exact:true}).count(),1)
   const visible=await panel.innerText()
   assert.ok(visible.includes('Source publication: 2026-09-12 (date only)'))
   assert.ok(visible.includes('2026-09-13 10:00:00.123456 UTC'))
   assert.ok(visible.includes('Shared origins are not independent corroboration.'))
   assert.ok(visible.includes('A dependency changed. Reassessment is pending'))
   for(const title of ['Likelihood','Confidence in this likelihood assessment','Diagnostic relevance','Evidence quality','Overall assessment confidence'])
    assert.ok(visible.includes(title))
   assert.ok(!visible.includes('50%'))
   assert.equal(await panel.evaluate(el=>el.scrollWidth>el.clientWidth+1),false)
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)
   const revision=panel.getByRole('heading',{name:'Saved revision record',exact:true})
   await revision.scrollIntoViewIfNeeded()
   const box=await revision.boundingBox()
   assert.ok(box.y>=0&&box.y+box.height<=1000)
   if(width===390)console.log('MIP_SYNTHETIC_SAVED_REVISION_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await panel.getByRole('heading',{name:'What explains the fictional contract award?',exact:true}).scrollIntoViewIfNeeded()
   if(width===390)console.log('MIP_SYNTHETIC_SAVED_ASSESSMENT_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await disclosure.focus();await page.keyboard.press('Enter')
   await panel.getByRole('heading',{name:'Saved revision record',exact:true}).waitFor({state:'detached'})
   await page.evaluate(()=>window.renderSyntheticComposer())
   assert.equal(await page.evaluate(()=>window.composerSynthetic.contextReads),0)
   await page.getByRole('button',{name:'Write a hypothesis assessment',exact:true}).click()
   const compose=page.getByRole('region',{name:'Compose hypothesis assessment'})
   await compose.waitFor()
   await compose.getByLabel('Definition of explanation 1',{exact:true}).fill('Synthetic explanation A.')
   await compose.getByLabel('Definition of explanation 2',{exact:true}).fill('Synthetic explanation B.')
   await compose.getByLabel('Retained material',{exact:true}).selectOption('9007199254740993')
   await compose.getByLabel('Retained text field',{exact:true}).selectOption('summary')
   await page.evaluate(()=>window.composerSynthetic.mode='bad_hash')
   await compose.getByRole('button',{name:'Open retained passage',exact:true}).click()
   await compose.getByRole('alert').waitFor()
   assert.equal(await compose.getByRole('button',{name:'Link this passage',exact:true}).count(),0)
   await page.evaluate(()=>window.composerSynthetic.mode='lost_ack')
   await compose.getByRole('button',{name:'Open retained passage',exact:true}).click()
   await compose.getByRole('button',{name:'Link this passage',exact:true}).click()
   await compose.getByLabel('What evidence 1 documents, within its limits',{exact:true}).fill('Synthetic passage records a meeting, not its purpose.')
   await compose.getByRole('button',{name:'Add argument',exact:true}).click()
   await compose.getByLabel('How the evidence relates',{exact:true}).selectOption('compatible')
   await compose.getByLabel('Evidence 1',{exact:true}).check()
   await compose.getByLabel('Inferential connection for argument 1',{exact:true}).fill('The synthetic meeting fits either explanation.')
   await compose.getByLabel('Limitations of argument 1',{exact:true}).fill('The synthetic discussion is unknown.')
   await compose.getByLabel('Comparison',{exact:true}).selectOption('difficult_to_distinguish')
   await compose.getByLabel('Saved comparison rationale',{exact:true}).fill('Synthetic alternatives remain difficult to distinguish.')
   await compose.getByLabel('Main limitation',{exact:true}).fill('Synthetic evaluation record is absent.')
   await compose.getByLabel('Reason for this saved revision',{exact:true}).fill('Synthetic initial human entry.')
   const overflow=await compose.evaluate(el=>({overflow:el.scrollWidth>el.clientWidth+1,width:el.clientWidth,scroll:el.scrollWidth,
    elements:[...el.querySelectorAll('*')].filter(n=>n.scrollWidth>n.clientWidth+1||n.getBoundingClientRect().right>el.getBoundingClientRect().right+1).map(n=>({tag:n.tagName,label:n.tagName==='LABEL'?n.firstChild?.textContent:null,classes:n.className,width:n.getBoundingClientRect().width,right:n.getBoundingClientRect().right,scroll:n.scrollWidth,client:n.clientWidth,overflow:getComputedStyle(n).overflow})).slice(0,12)}))
   if(overflow.overflow)console.log('MIP_SYNTHETIC_COMPOSER_LAYOUT_FAILURE='+JSON.stringify({engine,width,...overflow}))
   assert.equal(overflow.overflow,false)
   const saveButton=compose.getByRole('button',{name:'Save private assessment',exact:true})
   assert.ok((await saveButton.boundingBox()).height>=44)
   if(width===390){await compose.getByRole('heading',{name:'Competing explanations',exact:true}).scrollIntoViewIfNeeded();console.log('MIP_SYNTHETIC_COMPOSER_FORM_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))}
   await saveButton.click()
   const retry=page.getByRole('button',{name:'Retry the same assessment',exact:true})
   await retry.waitFor()
   assert.equal(await compose.count(),0)
   assert.equal(await page.getByText('Assessment saved privately. Human review and publication eligibility remain separate.',{exact:true}).count(),0)
   await retry.focus();await page.keyboard.press('Enter')
   await page.getByText('Assessment saved privately. Human review and publication eligibility remain separate.',{exact:true}).waitFor()
   const state=await page.evaluate(()=>window.composerSynthetic)
   assert.equal(state.contextReads,1);assert.equal(state.spanReads,2);assert.equal(state.submissions.length,2)
   assert.equal(state.commits,1);assert.deepEqual(state.submissions[0],state.submissions[1])
   const saved=state.saved.assessment
   assert.equal(saved.review_state,'unreviewed');assert.equal(saved.release_state,'private')
   assert.equal(saved.evidence[0].input_position,'9007199254740993')
   assert.equal(saved.evidence[0].source_span.end,Array.from('Synthetic meeting 🧭.').length)
   assert.ok(!JSON.stringify(state.submissions).includes('Synthetic meeting 🧭.'))
   assert.equal(saved.arguments[0].relation,'compatible')
   assert.equal(saved.arguments[0].evidence_ids[0],saved.evidence[0].id)
   assert.equal(saved.comparison.confidence.kind,'not_estimated')
   await page.evaluate(()=>window.inspectSyntheticSaved())
   await panel.getByText('Synthetic alternatives remain difficult to distinguish.',{exact:true}).waitFor()
   await panel.locator('summary').click()
   await panel.getByText('Synthetic passage records a meeting, not its purpose.',{exact:false}).waitFor()
   if(width===390)console.log('MIP_SYNTHETIC_COMPOSER_SAVED_'+engine+'='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'))
   await page.evaluate(()=>window.renderSyntheticComposer(null))
   await panel.waitFor({state:'detached'})


  }
  assert.deepEqual(requests,[]);assert.deepEqual(errors,[])
  console.log('MIP_SYNTHETIC_HYPOTHESIS_BROWSER_PASS='+JSON.stringify({engine,widths:[1280,768,390,320],
   keyboardInspection:true,reciprocalRecoveryLinks:true,onlyUnlinkedFailureRecoverable:true,
   noAutomaticRetry:true,deniedRecordsCleared:true,logoutCleared:true,networkRequests:0,
   composerExactUnicodeSpan:true,hashMismatchDenied:true,linkedReasoning:true,lostAcknowledgementExactRetry:true,syntheticReceiptOnly:true,savedRevisionReachableByScrolling:true,savedAssessmentDisclosure:true,separateMissingEstimates:true,sourceClocks:true,pendingReassessment:true,systemFontFallback:true,scope:'synthetic_ledger_saved_assessment_and_composer',productionQualified:false}))
 }finally{await browser.close()}
}
