-- Production-recorded public-surface transfer chunk.
-- Applied on qikvmopbtijoebdqosyq as 20260905172543 / mip_public_surface_tables.
-- Restored verbatim from supabase_migrations.schema_migrations.statements.
-- Do not replay this file on production; it is already recorded there.

create table if not exists public.topics (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, parent_id uuid references public.topics (id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.node_topics (node_id uuid not null references public.nodes (id) on delete cascade, topic_id uuid not null references public.topics (id) on delete cascade, confidence numeric not null default 0.5, created_at timestamptz not null default now(), primary key (node_id, topic_id));
create table if not exists public.entities (id uuid primary key default gen_random_uuid(), canonical_name text not null, normalized_name text not null, aliases text[] not null default '{}'::text[], entity_type text not null default 'other', mention_count integer not null default 0, created_at timestamptz not null default now(), last_seen timestamptz not null default now());
create table if not exists public.policy_topics (policy_id uuid not null references public.policies (id) on delete cascade, topic_id uuid not null references public.topics (id) on delete cascade, confidence numeric not null default 0.5, created_at timestamptz not null default now(), primary key (policy_id, topic_id));
create table if not exists public.policy_actors (policy_id uuid not null references public.policies (id) on delete cascade, entity_id uuid not null references public.entities (id) on delete cascade, role text not null default 'issuing_authority', created_at timestamptz not null default now(), primary key (policy_id, entity_id, role));
alter table public.policy_actors add column if not exists actor_id uuid generated always as (entity_id) stored;
create table if not exists public.arc_events (id uuid primary key default gen_random_uuid(), arc_id uuid not null references public.story_arcs (id) on delete cascade, title text not null, category text not null, confidence text not null default 'confirmed', occurred_at date, description text, arc_membership_candidate_id uuid references public.arc_membership_candidates (id));
create table if not exists public.arc_milestones (id uuid primary key default gen_random_uuid(), arc_id uuid not null references public.story_arcs (id) on delete cascade, title text not null, status text not null default 'pending' check (status in ('pending', 'confirmed', 'failed', 'abandoned')), notes text, updated_at timestamptz not null default now(), milestone_key text);
create table if not exists public.citations (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles (id) on delete cascade, cited_entity text not null, cited_type text not null, documentation_strength numeric not null, resolved_node_id uuid references public.nodes (id), created_at timestamptz not null default now());
create table if not exists public.sky_verifications (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles (id) on delete cascade, arc_id uuid references public.story_arcs (id) on delete set null, observed_azimuth_deg numeric(6,2) not null, observed_altitude_deg numeric(5,2) not null, captured_at timestamptz not null, centroid_lat numeric(9,6), centroid_lng numeric(9,6), confidence_radius_km numeric(7,2) not null, sensor_quality text not null check (sensor_quality in ('high','medium','low')), angular_error_deg numeric(4,2), image_hash text not null, method text not null default 'shadow_assisted' check (method in ('shadow_assisted','shadow_auto','sky_disk','star_field')), created_at timestamptz not null default now());
create table if not exists public.events (id uuid primary key default gen_random_uuid(), canonical_title text not null, occurred_at_start date, occurred_at_end date, location_text text, arc_id uuid references public.story_arcs (id), arc_event_id uuid references public.arc_events (id), status text not null default 'candidate', rule_version text, created_at timestamptz not null default now(), comparison_validation_state text not null default 'pending_review' check (comparison_validation_state in ('pending_review', 'approved', 'quarantined', 'not_applicable')));
comment on table public.events is 'Source Comparison event family. Distinct from public.nodes of type event. UUIDs are not interchangeable.';
comment on column public.events.comparison_validation_state is 'Reader-facing Source Comparison admission state. pending_review and quarantined events are withheld from comparison_public.';
create table if not exists public.claims (id uuid primary key default gen_random_uuid(), event_id uuid references public.events (id), canonical_text text not null, claim_kind text not null default 'fact', thin_extraction boolean not null default false, status text not null default 'active', rule_version text, first_seen_at timestamptz not null default now(), created_at timestamptz not null default now());
create table if not exists public.article_claims (id uuid primary key default gen_random_uuid(), claim_id uuid not null references public.claims (id), article_id uuid not null references public.articles (id), surface_text text not null, char_start integer, char_end integer, extraction_method text not null default 'existing_claims_jsonb', extraction_confidence numeric, stance text not null default 'asserts', loaded_language jsonb not null default '[]'::jsonb, version integer not null default 1, is_current boolean not null default true, created_at timestamptz not null default now(), evidence_source_field text, evidence_excerpt text, auditability_state text not null default 'unverified_against_retained_source', auditability_note text, unique (claim_id, article_id, version));
create table if not exists public.event_articles (event_id uuid not null references public.events (id), article_id uuid not null references public.articles (id), membership_method text not null, membership_confidence numeric, created_at timestamptz not null default now(), primary key (event_id, article_id));
create table if not exists public.claim_evidence_links (id uuid primary key default gen_random_uuid(), claim_id uuid not null references public.claims (id), evidence_url text not null, evidence_type text not null default 'other', linked_from_article_id uuid references public.articles (id), created_at timestamptz not null default now());
create table if not exists public.claim_corrections (id uuid primary key default gen_random_uuid(), claim_id uuid not null references public.claims (id), correcting_article_id uuid not null references public.articles (id), corrected_article_id uuid references public.articles (id), correction_text text, detected_method text not null default 'manual', occurred_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.explanations (id uuid primary key default gen_random_uuid(), assertion_id text not null, assertion_type text not null, version integer not null, is_current boolean not null default true, source_ids uuid[] not null default '{}'::uuid[], archived_sources jsonb not null default '[]'::jsonb, source_roles jsonb not null default '{}'::jsonb, supporting_passage text, contradicting_evidence jsonb not null default '[]'::jsonb, missing_evidence jsonb not null default '[]'::jsonb, shared_entities uuid[] not null default '{}'::uuid[], relationship_type text, rule_version text, provenance_class text not null, created_at timestamptz not null default now(), recomputed_at timestamptz, reviewed_at timestamptz, review_status text not null default 'draft', falsification_condition text, correction_history jsonb not null default '[]'::jsonb, remaining_uncertainty text, state text not null default 'explanation_pending');
create table if not exists public.cross_surface_candidates (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles (id), candidate_type text not null, target_table text not null, target_id uuid, evidence_excerpt text not null, evidence_start integer, evidence_end integer, algorithm_version text not null, review_state text not null default 'pending', remaining_uncertainty text not null, created_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by text);
create table if not exists public.node_location_mentions (id uuid primary key default gen_random_uuid(), node_id uuid not null references public.nodes (id) on delete cascade, article_id uuid references public.articles (id), event_id uuid, place_id uuid references public.geographic_places (id), mention_text text not null, text_field text not null, mention_start integer, mention_end integer, location_role text not null, literal_status text not null, resolution_method text not null, review_state text not null, remaining_uncertainty text, extraction_version text not null default 'geography-v1', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
comment on column public.node_location_mentions.event_id is 'Optional Source Comparison event family id. Not a public.nodes id.';
create table if not exists public.p3_legal_case (id uuid primary key default gen_random_uuid(), title text not null, case_status text not null, verdict_or_disposition text, charge_or_issue text, deciding_body text, appeal_status text, involves_minor_or_private_person boolean not null default false, sealed_or_expunged boolean not null default false, authentication_completeness text, remaining_uncertainty text, review_status text not null, reviewed_by text, reviewed_at timestamptz, correction_notice text, correction_history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now());
create table if not exists public.p3_legal_case_evidence (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.p3_legal_case (id) on delete cascade, track text not null, description text not null, source_id uuid, source_passage text, method_version text, authentication_state text, remaining_uncertainty text, review_status text not null, reviewed_by text, reviewed_at timestamptz, correction_notice text, correction_history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), source_url text);
create table if not exists public.p3_policy (id uuid primary key default gen_random_uuid(), name text not null, jurisdiction text, instrument_type text, description text, review_status text not null default 'draft', reviewed_by text, reviewed_at timestamptz, correction_notice text, correction_history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), agency text, source_locator jsonb);
create table if not exists public.p3_policy_track_event (id uuid primary key default gen_random_uuid(), policy_id uuid not null references public.p3_policy (id) on delete cascade, track text not null, state text not null, event_date date, source_id uuid, source_passage text, method_version text, remaining_uncertainty text, missing_evidence boolean not null default false, review_status text not null default 'draft', reviewed_by text, reviewed_at timestamptz, correction_notice text, correction_history jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), source_locator jsonb);
create table if not exists public.mip_consolidation_watermarks (source_project_ref text not null, channel text not null, watermark jsonb not null, captured_at timestamptz not null default now(), primary key (source_project_ref, channel));
comment on table public.mip_consolidation_watermarks is 'Capture watermarks for Manus collectors. Does not start or stop workers.';
