-- Production-recorded public-surface transfer chunk.
-- Applied on qikvmopbtijoebdqosyq as 20260905172611 / mip_public_surface_views.
-- Restored verbatim from supabase_migrations.schema_migrations.statements.
-- Do not replay this file on production; it is already recorded there.

create or replace view public.authors_public with (security_barrier = true, security_invoker = false) as select a.id, a.name from public.authors a;
create or replace view public.arc_milestones_public with (security_barrier = true, security_invoker = false) as select m.id, m.arc_id, m.title, m.status, m.notes, m.updated_at from public.arc_milestones m where mip_private.arc_has_approved_membership(m.arc_id);
create or replace view public.graph_coverage_public with (security_barrier = true, security_invoker = false) as
with article_totals as (select count(*)::integer as article_count from public.articles),
resolved_article_totals as (select count(distinct c.article_id)::integer as articles_with_published_node from public.citations c where c.article_id is not null and c.resolved_node_id is not null),
pending_graph_candidates as (select count(*)::integer as pending_graph_candidate_count from public.cross_surface_candidates c where c.candidate_type in ('graph_node', 'graph_edge') and c.review_state in ('pending', 'owner_hold')),
published_graph as (select (select count(*)::integer from public.nodes) as published_node_count, (select count(*)::integer from public.edges) as documented_relationship_count)
select a.article_count, r.articles_with_published_node, greatest(a.article_count - r.articles_with_published_node, 0)::integer as articles_without_published_node, p.pending_graph_candidate_count, g.published_node_count, g.documented_relationship_count
from article_totals a cross join resolved_article_totals r cross join pending_graph_candidates p cross join published_graph g;
create or replace view public.news_detail_public with (security_barrier = true, security_invoker = false) as
select a.id as article_id, coalesce((select jsonb_agg(jsonb_build_object('surface_text', ac.surface_text, 'canonical_text', c.canonical_text, 'auditability_state', ac.auditability_state, 'auditability_note', ac.auditability_note, 'evidence_source_field', ac.evidence_source_field, 'evidence_excerpt', ac.evidence_excerpt, 'evidence_records', coalesce((select jsonb_agg(jsonb_build_object('evidence_url', cel.evidence_url, 'evidence_type', cel.evidence_type) order by cel.evidence_type, cel.evidence_url) from public.claim_evidence_links cel where cel.claim_id = c.id), '[]'::jsonb)) order by ac.id) from public.article_claims ac join public.claims c on c.id = ac.claim_id where ac.article_id = a.id and ac.is_current = true), '[]'::jsonb) as reviewed_claims
from public.articles a where a.reader_state = 'eligible' and a.source_status = 'active';
create or replace view public.comparison_public with (security_barrier = true, security_invoker = false) as
select md5(e.id::text) as event_key, e.canonical_title, e.occurred_at_start, e.occurred_at_end,
coalesce((select jsonb_agg(article_row.article order by article_row.published_at nulls last, article_row.article_key) from (select a.published_at, md5(a.id::text) as article_key, jsonb_build_object('article_key', md5(a.id::text), 'outlet', a.outlet, 'article_url', a.url, 'published_at', a.published_at, 'arc_slug', arc.slug, 'arc_title', arc.title, 'timeline_key', timeline.timeline_key, 'has_extracted_claim', exists (select 1 from public.article_claims existing_surface join public.claims existing_claim on existing_claim.id = existing_surface.claim_id where existing_surface.article_id = a.id and existing_surface.is_current = true and existing_claim.status = 'active' and existing_claim.rule_version = 'sc-v2-event-projection')) as article from public.event_articles ea join public.articles a on a.id = ea.article_id left join public.story_arcs arc on arc.id = a.arc_id left join lateral (select right(n.slug, 8) as timeline_key from public.nodes n where n.type = 'event' and n.arc_id = a.arc_id order by (n.slug like 'evt-%') desc, n.slug limit 1) timeline on true where ea.event_id = e.id and a.reader_state = 'eligible' and a.source_status = 'active') article_row), '[]'::jsonb) as articles,
coalesce((select jsonb_agg(claim_row.claim order by claim_row.canonical_text) from (select c.canonical_text, jsonb_build_object('claim_key', md5(c.id::text), 'canonical_text', c.canonical_text, 'thin_extraction', c.thin_extraction, 'surfaces', coalesce((select jsonb_agg(surface_row.surface order by surface_row.published_at nulls last, surface_row.article_key) from (select a.published_at, md5(a.id::text) as article_key, jsonb_build_object('article_key', md5(a.id::text), 'surface_text', ac.surface_text, 'loaded_language', ac.loaded_language, 'explanation', explanation.explanation) as surface from public.article_claims ac join public.articles a on a.id = ac.article_id left join lateral (select jsonb_build_object('supporting_passage', x.supporting_passage, 'rule_version', x.rule_version, 'provenance_class', x.provenance_class, 'reviewed_at', x.reviewed_at, 'review_status', x.review_status, 'state', x.state, 'remaining_uncertainty', x.remaining_uncertainty) as explanation from public.explanations x where x.assertion_type = 'claim_grouping' and x.is_current = true and x.rule_version like 'sc-v2-event-projection|%' and right(x.assertion_id, 36) = ac.article_id::text and position(format('Surface claim "%s" grouped under canonical "', ac.surface_text) in coalesce(x.supporting_passage, '')) = 1 order by x.recomputed_at desc nulls last, x.id limit 1) explanation on true where ac.claim_id = c.id and ac.is_current = true and a.reader_state = 'eligible' and a.source_status = 'active') surface_row), '[]'::jsonb), 'evidence_links', coalesce((select jsonb_agg(jsonb_build_object('evidence_url', cel.evidence_url, 'evidence_type', cel.evidence_type) order by cel.evidence_type, cel.evidence_url) from public.claim_evidence_links cel where cel.claim_id = c.id), '[]'::jsonb), 'corrections', coalesce((select jsonb_agg(jsonb_build_object('correction_text', cc.correction_text, 'occurred_at', cc.occurred_at) order by cc.occurred_at nulls last) from public.claim_corrections cc where cc.claim_id = c.id), '[]'::jsonb)) as claim from public.claims c where c.event_id = e.id and c.status = 'active' and c.rule_version = 'sc-v2-event-projection') claim_row), '[]'::jsonb) as claims
from public.events e where e.status <> 'timeline_only' and e.comparison_validation_state = 'approved' and exists (select 1 from public.event_articles ea join public.articles a on a.id = ea.article_id where ea.event_id = e.id and a.reader_state = 'eligible' and a.source_status = 'active' group by ea.event_id having count(distinct a.outlet) >= 2);
revoke all on public.authors_public, public.arc_milestones_public, public.graph_coverage_public, public.news_detail_public, public.comparison_public from public;
grant select on public.authors_public, public.arc_milestones_public, public.graph_coverage_public, public.news_detail_public, public.comparison_public to anon, authenticated, service_role;
comment on view public.authors_public is 'Anonymous author byline contract. Private author profiling columns stay on authors.';
comment on view public.arc_milestones_public is 'Anonymous milestone contract. Rows appear only for arcs with an approved membership candidate.';
comment on view public.graph_coverage_public is 'Anonymous aggregate coverage disclosure. Counts stored publication and review states only.';
comment on view public.news_detail_public is 'Anonymous News-detail contract. Pending and non-active articles are withheld.';
comment on view public.comparison_public is 'Anonymous Source Comparison contract. Requires approved comparison_validation_state, two eligible outlets, and does not join graph node ids.';
